app/build.gradle
app/src/main/java/dev/patrickgold/florisboard/ime/core/FlorisBoard.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/PrefHelper.kt
app/src/main/java/dev/patrickgold/florisboard/ime/editing/EditingKeyView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/editing/EditingKeyboardView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/media/MediaInputManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/TextInputManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/smartbar/SmartbarManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/smartbar/SmartbarView.kt
app/src/main/res/drawable/button_key_enable_color_selector.xml
app/src/main/res/drawable/button_transparent_bg_on_press_with_border.xml
app/src/main/res/drawable/ic_arrow_back.xml
app/src/main/res/drawable/ic_content_copy.xml
app/src/main/res/drawable/ic_content_cut.xml
app/src/main/res/drawable/ic_content_paste.xml
app/src/main/res/drawable/ic_first_page.xml
app/src/main/res/drawable/ic_format_italic.xml
app/src/main/res/drawable/ic_last_page.xml
app/src/main/res/drawable/ic_select_all.xml
app/src/main/res/layout/editing_layout.xml
app/src/main/res/layout/smartbar.xml
app/src/main/res/layout/text_input_layout.xml
app/src/main/res/values/arrays.xml
app/src/main/res/values/attrs.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml
app/src/main/res/values/themes.xml
app/src/main/res/xml/prefs_keyboard.xml

This PR adds a clipboard/cursor keyboard layout (accessible via Smartbar quick actions) and the ability to show a number row or clipboard cursor toolbar above the keyboard if candidate suggestions are disabled.
Editing keyboard layout:
Smartbar clipboard/cursor toolbar (#9):
Number row (#3):

Add clipboard cursor related tools

---

app/src/main/java/dev/patrickgold/florisboard/ime/core/EditorInstance.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/key/KeyView.kt
app/src/main/res/values/arrays.xml

https://user-images.githubusercontent.com/20506602/103137817-7f7f2100-46f2-11eb-9703-caa2eeef7a66.mp4
https://user-images.githubusercontent.com/20506602/103137820-86a62f00-46f2-11eb-961f-64920cd0a1d4.mp4
https://user-images.githubusercontent.com/20506602/103137824-8c037980-46f2-11eb-89d8-7cd450c6122f.mp4
closes #25

Delete Key gesture Improvents

---

app/src/main/java/dev/patrickgold/florisboard/ime/text/key/KeyView.kt

https://user-images.githubusercontent.com/20506602/103139783-c6c2dd00-4705-11eb-8db4-4cf5dc87c851.mp4
https://user-images.githubusercontent.com/20506602/103139786-d2ae9f00-4705-11eb-92b6-462e8a41cad7.mp4

Fix left and right arrow in clipboard cursor row

---

app/src/main/java/dev/patrickgold/florisboard/ime/core/EditorInstance.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/TextInputManager.kt
app/src/main/res/drawable/ic_redo.xml
app/src/main/res/drawable/ic_undo.xml
app/src/main/res/layout/smartbar.xml
app/src/main/res/values/strings.xml

On Whatsapp, telegram and chrome, It works without any issues.
On Keep notes, it works but Quick Action Bar automatically closes after single-use (This shouldn't happen and I can't figure out why it does so) 
https://user-images.githubusercontent.com/20506602/103149604-e4895400-4790-11eb-84c6-53d69df6ad30.mp4
closes #70

Added Undo Redo Buttons to Quick Actions in Smart Bar

---

app/src/main/assets/ime/theme/floris_day.json
app/src/main/assets/ime/theme/floris_night.json
app/src/main/java/dev/patrickgold/florisboard/ime/core/EditorInstance.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/PrefHelper.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/TextInputManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/smartbar/SmartbarQuickActionButton.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/smartbar/SmartbarView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/theme/Theme.kt
app/src/main/res/drawable/ic_security.xml
app/src/main/res/layout/smartbar.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml
app/src/main/res/xml/prefs_advanced.xml
app/src/main/res/xml/prefs_theme.xml

This PR adds a basic implementation of a private mode, which prevents features from temporarily saving the input data. This affects the clipboard history (NYI), clipboard suggestions and the next word algorithm adjustments (NYI). The private mode activates either if an app requests it or if the "Force private mode" flag is set in the Advanced Settings. In its current state also rather useless, but it will get important as soon as the composing suggestions are up and running. Below is a screenshot how the indication for the private mode looks like (purple icon in the Smartbar).
Closes #106

Add private mode (aka incognito mode) base

---

app/src/main/java/dev/patrickgold/florisboard/ime/core/PrefHelper.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/key/KeyHintMode.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/key/KeyView.kt
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-cs/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-el/strings.xml
app/src/main/res/values-fa/strings.xml
app/src/main/res/values-fi/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-hu/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-pt-rBR/strings.xml
app/src/main/res/values-pt/strings.xml
app/src/main/res/values/arrays.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/prefs_keyboard.xml

This PR is finally a solution for the discussion, whether a hinted symbol or the accent character should take priority in the extended popup. The preference toggles for the hinted number row and the hinted symbols have been replaced by a hint priority setting for both, which can separately be set to `Disabled`, `Enabled (Hint takes priority)` and `Enabled (Accent takes priority)`.
In the future it is also planned to add an `Enabled (Smart prioritization)` mode, which decides based on the current subtype, which of the two possibilities should be selected.
Closes #39

Add hint priority mode setting

---

app/src/main/assets/ime/config.json
app/src/main/assets/ime/text/characters/bepo.json

Closes #181 
This layout has a large bottom line so thin shift and backspace keys would be great.
Also, i only implemented first layer characters so long-press chars are not yet customized for bépo.

Add Bépo french keyboard layout

---

app/src/main/java/dev/patrickgold/florisboard/ime/text/key/KeyView.kt

This PR fixes a common issue with the key width of shift and delete for 9+ character keys in between by reducing the width of those 2 keys. Relevant #202. 8 characters or less will have the default delete/shift width.
Closes #205 
| 7 characters inbetween | 8 characters inbetween |
|------------------------|---------------------------|
| ![delete-shift-key-width-9char](https://user-images.githubusercontent.com/19412843/104949796-d1e4f200-59bf-11eb-9e94-04ae91b9cba4.jpg) | ![delete-shift-key-width-10char](https://user-images.githubusercontent.com/19412843/104949808-d7dad300-59bf-11eb-9068-172185bab8a2.jpg) |
| 9 characters inbetween | 10 characters inbetween |
|------------------------|---------------------------|
|  ![delete-shift-key-width-11char](https://user-images.githubusercontent.com …

Fix delete and shift key width for 9+ char rows

---

app/src/main/assets/ime/text/characters/extended_popups/pt-BR.json

Objectives of this PR:
1. Order the extended popups characters according to the order seen on the `Gboard`.
2. Add the `.br` extension.
- Note 1: I'm not a programmer so this might have some errors.
- Note 2: I did not change the `config.json` because the `pt-BR` language is already there.

Trying to add Brazilian Portuguese (pt-BR) Layout

---

app/src/main/java/dev/patrickgold/florisboard/ime/text/gestures/SwipeGesture.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/key/KeyView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/KeyboardView.kt
app/src/main/res/xml/prefs_gestures.xml

This PR is an attempt to fix the precise character deletion behavior for the delete key. Until now, the amount of characters the swipe selected was dependent on the speed of the swipe as well as on the current CPU load. Now, the amount of characters is calculated based on the distance you swiped and thus the behavior is way more consistent in all situations, independent of the speed and CPU load.
Closes #154 
The delete swipe is now also generally more fast and accurate, similar to OpenBoard or Gboard. Please note that the amount of charcters is dependent on the `Swipe distance threshold` value in the Gesture preferences.
Closes #124 
https://user-images.githubusercontent.com/19412843/105382125-0a7b0a80-5c10-11eb-9ef2-7780258a4fcd.mp4

Fix precise character deletion behaviour

---

app/src/main/java/dev/patrickgold/florisboard/ime/text/TextInputManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/key/KeyView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/KeyboardView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/layout/LayoutData.kt
app/src/main/res/layout/text_input_layout.xml
app/src/main/res/values/attrs.xml

This PR adds a proper loading placeholder keyboard, which replaces the old "Loading keyboard, please wait..." screen. Additionally, the selection keyboard flash bug has been eliminated. Many thanks to @Glitchy-Tozier who gave me a lot of ideas and helped in testing and fine-tuning the animation. Note, that the animation is visible to devices of all "speed" classes, but especially for older devices this should be a more pleasant loading screen than the old ugly screen.
For screen recordings of the animation see the last ones in the referenced issue.
Closes #207

Proper loading keyboard animation

---

app/src/main/java/dev/patrickgold/florisboard/ime/text/key/KeyView.kt

This PR fixes the space bar long press action in several ways:
- The long press delay is now exactly twice as long as the time set in the preferences. This ensures that it is more difficult to accidentally trigger the long-press action while using the space swipe left/right. The long-press time of any other key is not affected by this change.
- `No action` as well as `Insert space` now both insert a space exactly when the space bar is released, regardless how long it has been pressed. This enables the space bar to behave like a space bar when set to these cases. Previously, `No action` did nothing and `Insert space` did insert the space after exactly the `delay time` set in the preferences, which is not how this should behave. Both actions do not block the swipe left/right action. Closes …

Fix space bar long press

---

app/src/main/java/dev/patrickgold/florisboard/ime/theme/Theme.kt
app/src/main/java/dev/patrickgold/florisboard/settings/ThemeEditorActivity.kt
app/src/main/java/dev/patrickgold/florisboard/settings/components/ThemeAttrGroupView.kt
app/src/main/java/dev/patrickgold/florisboard/settings/components/ThemeAttrView.kt
app/src/main/res/layout/theme_editor_activity.xml
app/src/main/res/layout/theme_editor_attr_dialog.xml
app/src/main/res/layout/theme_editor_group_dialog.xml
app/src/main/res/values-ar/strings.xml
app/src/main/res/values-cs/strings.xml
app/src/main/res/values-da/strings.xml
app/src/main/res/values-de/strings.xml
app/src/main/res/values-el/strings.xml
app/src/main/res/values-eo/strings.xml
app/src/main/res/values-es/strings.xml
app/src/main/res/values-fa/strings.xml
app/src/main/res/values-fi/strings.xml
app/src/main/res/values-fr/strings.xml
app/src/main/res/values-he/strings.xml
app/src/main/res/values-hu/strings.xml
app/src/main/res/values-it/strings.xml
app/src/main/res/values-ku/strings.xml
app/src/main/res/values-nl/strings.xml
app/src/main/res/values-pt-rBR/strings.xml
app/src/main/res/values-pt/strings.xml
app/src/main/res/values-ru/strings.xml
app/src/main/res/values/strings.xml

This PR is an attempt at improving the theme editor UI and UX. In detail, this is what changed:
- The theme editor now has a help icon in the top right corner which leads to [this](https://github.com/florisboard/florisboard/wiki/Using-the-new-Theme-Editor) wiki entry. The referenced wiki entry is a guide to better understand some of the more complex things you can do with the theme editor, which may not be known upfront.
- Group name and attribute name inputs now also check if the given name already exists. While this didn't lead to crashes, duplicate attributes and groups overrode each other and created strange results. This is now not possible anymore and eliminates a possible error source.
- The group and attribute names now display localized strings instead of the raw English names. …

Improve theme editor UI and UX

---

app/src/main/java/dev/patrickgold/florisboard/ime/text/key/KeyView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/theme/AdaptiveThemeOverlay.kt
app/src/main/java/dev/patrickgold/florisboard/ime/theme/ThemeManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/theme/ThemeValue.kt
app/src/main/java/dev/patrickgold/florisboard/settings/components/ThemeAttrView.kt
app/src/main/res/layout/theme_editor_attr_dialog.xml

This PR improves adaptive themeing and additionally fixes small bugs in the theme engine and editor. In detail, this is what changed:
- The adaptive theme process now is more consistent and checks for the `targetActivity` attribute. Also, if the launch activity has no theme set, the application is checked if a theme is set there. This makes the colors more consistent and for most apps colors are found.
- All parsed colors are forced to be non-transparent to fix issues with see-through keyboards.
- The key `foregroundPressed` attribute is now applied when the key is pressed (was previously ignored in some circumstances).
- The Smartbar `foregroundAlt` attribute now also adapts to the target app theme.
- The navigation bar foreground now also adapts the the background color parsed from the …

Improve adaptive theme / Fix color dialog cache bug in theme editor

---

app/src/main/java/dev/patrickgold/florisboard/ime/core/FlorisBoard.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/PrefHelper.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/TextInputManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/key/KeyView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/key/SwitchKeyMode.kt
app/src/main/res/values/arrays.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/prefs_keyboard.xml

This PR adds the ability to customize the switch key (emoji key / language switch key) by setting the `Switch key mode` preference in Settings > Keyboard.
The following modes are available:
- `Never show switch`: Completely disables the switch key and thus expands the space bar.
- `Emoji switch`: Always shows the emoji key.
- `Language switch (Internal)`: Cycles through the FlorisBoard internal subtypes. Note, that this key will not do anything if less or equal than 1 subtype is active in FlorisBoard.
- `Language switch (System)`: Switches to the next system subtype (is a subtype of another keyboard).
- `Dynamic emoji / language switch (Internal)`: Same as the `Language switch (Internal)`, but for the instances where the language switch would do nothing, the emoji key is shown. This is …

Add ability to customize switch key (emoji, language)

---

app/src/main/java/dev/patrickgold/florisboard/ime/core/PrefHelper.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/TextInputManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/key/KeyView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/key/UtilityKeyAction.kt
app/src/main/java/dev/patrickgold/florisboard/settings/fragments/KeyboardFragment.kt
app/src/main/res/values/arrays.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/prefs_keyboard.xml

This PR is an attempt to fix the utility key naming scheme (previously called "Switch key mode"). See attached screenshots below for what has changed. As the preference keys for this feature have changed, this causes the "Switch key mode" to completely reset. Sorry for the inconvenience.
Closes #246 
Old | New (Disabled) | New (Enabled) | New (Utility key actions)
---|---|---|---
_((( no idea what GitHub does with the column widths... )))_

Fix utility key naming

---

app/src/main/assets/ime/theme/floris_day.json
app/src/main/assets/ime/theme/floris_day_borderless.json
app/src/main/assets/ime/theme/floris_night.json
app/src/main/assets/ime/theme/floris_night_borderless.json
app/src/main/java/dev/patrickgold/florisboard/ime/core/FlorisBoard.kt
app/src/main/java/dev/patrickgold/florisboard/ime/popup/PopupLayerView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/theme/Theme.kt
app/src/main/java/dev/patrickgold/florisboard/settings/ThemeEditorActivity.kt
app/src/main/java/dev/patrickgold/florisboard/util/view_utils.kt
app/src/main/res/layout/florisboard.xml
app/src/main/res/values/strings.xml

This PR adds support for the extract edit layout, which shows in landscreen mode when the app requests it. Previously, this was default implemented, but the textures were transparent and the extracted edit layout as a whole was buggy. Now, the layout integrates with the keyboard and provides theme attributes.
This also fixes #269, where the popups were displaced due to internal height changes.
```
"extractEditLayout": {
"background": "",
"foreground": "",
"foregroundAlt": ""
},
"extractActionButton": {
"background": "",
"foreground": ""
}
```

Add ExtractEditLayout support

---

app/build.gradle
app/src/debug/res/values/strings.xml
app/src/main/AndroidManifest.xml
app/src/main/java/dev/patrickgold/florisboard/ime/core/FlorisBoard.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/PrefHelper.kt
app/src/main/java/dev/patrickgold/florisboard/ime/landscapeinput/LandscapeInputUiMode.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/TextInputManager.kt
app/src/main/java/dev/patrickgold/florisboard/settings/SettingsMainActivity.kt
app/src/main/res/drawable/edit_text_background.xml
app/src/main/res/layout/about_activity.xml
app/src/main/res/values/arrays.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/prefs_keyboard.xml

This PR is an attempt to further improve the landscape input UI (formerly known as "Extract edit layout"). In detail, this has changed:
1. The landscape input UI has improved a tad and now looks like this:
2. The landscape input UI should now also theme correctly on Samsung devices (tested on a physical Samsung Galaxy A20e). (Closes #307)
3. The visibility of the landscape input UI can now be configured in Settings > Landscape fullscreen input (Closes #291)

Improve Landscape Input UI

---

app/src/main/assets/ime/text/characters/bepo.json

Those keys have two uses : 
* Be present
* They move the existing keys so that they are correctly aligned. In standard bépo, H,F are right below N,M. That's currently not the case.

Edit bépo layout to add "êà" keys

---

app/src/main/java/dev/patrickgold/florisboard/ime/core/FlorisBoard.kt

Resolves #255.
My original plan was to check for the device's haptics support, and use that information to determine whether or not haptic feedback should be enabled by default. A separate setting was to be provided in FlorisBoard settings, labeled "Use haptic feedback for vibration", which would be enabled if the device supported haptic feedback and disabled otherwise. This didn't pan out, as there's no function that can query whether or not a device supports haptic feedback.
As a result, I've elected to modify the default vibration behavior when a user taps a key. If the vibration strength is set to "System default", the device will first attempt to perform haptic feedback; if it succeeds, the vibration function completes. If the attempt fails, the function will fallback to the old …

Use haptic feedback by default if available

---

.gitattributes

This prevents `gradlew.bat` from being reset to LF line endings, which aren't guaranteed to be interpreted correctly by Windows CMD.

Add exception for bat files to gitattributes

---

app/src/main/java/dev/patrickgold/florisboard/ime/core/PrefHelper.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/TextInputManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/key/KeyView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/KeyboardRowView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/KeyboardView.kt
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/prefs_keyboard.xml

Hello :) 
I wanted to implement proposal #67 because I kinda wanted the feature as well. So, I've added options to to adjust the key spacing like this:
I chose 0.5 dp as the unit because unfortunately a full dp is a bit big.
As an example,
Before (spacing 2dp, 5dp):  
After (spacing 4dp, 4dp):
(There's a bit more space between the columns, it looks a bit more even)
This is my first contribution here so let me know if I need to change something :)
---
Closes #67 
Closes #354

Add options for key spacing

---

app/src/main/java/dev/patrickgold/florisboard/ime/core/EditorInstance.kt
app/src/main/java/dev/patrickgold/florisboard/ime/dictionary/Flictionary.kt
app/src/main/java/dev/patrickgold/florisboard/ime/nlp/FlorisLanguageModel.kt
app/src/main/java/dev/patrickgold/florisboard/ime/nlp/StagedSuggestionList.kt

This PR is a response to the reported memory crashes in #403 and attempts to fix them. In detail, this is what has been improved:
- The Flictionary load function previously created a lot of unnecessary allocations which it does not need. Additionally, the input stream of the binary raw file is now read as a stream, instead of per-caching the whole file before working with it.
- The NgramNode representation has also changed, so each node is much smaller in memory size than before. Also, the child nodes are now stored in an ArrayList rather than a LinkedHashMap, which vastly reduces the allocated memory size.

Fix memory management for Flictionaries & prediction algorithm

---

.editorconfig
app/build.gradle.kts
app/src/main/java/dev/patrickgold/florisboard/ime/core/EditorInstance.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/FlorisBoard.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/InputEventDispatcher.kt
app/src/main/java/dev/patrickgold/florisboard/ime/media/MediaInputManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/media/emoji/EmojiKeyView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/TextInputManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/editing/EditingKeyView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/editing/EditingKeyboardView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/gestures/SwipeGesture.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/key/KeyCode.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/key/KeyData.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/key/KeyView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/KeyboardView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/smartbar/SmartbarView.kt

This PR is a rather big one, as it reworks a ton of the backend input logic, adds support for multiple input touch pointers at once and adds some cool new frontend features. In detail, this is what changed:
- Input events of pressed keys are now guaranteed to execute in the order pressed and cannot overlap each other, thus preventing some weird state bugs. State bugs such as #227 can still occur because the `onUpdateSelection` callback is called asynchronously a few milliseconds later.
- The touch logic supports multiple input pointers now (preparation for glide typing) and in general the touch detection code has been cleaned up. Further refactoring needs to be done to completely clean up the touch logic code and improve its performance.
- The core class FlorisBoard now implements a …

Input logic rework

---

app/src/main/assets/ime/text/characters/colemak.json
app/src/main/assets/ime/text/characters/dvorak.json
app/src/main/java/dev/patrickgold/florisboard/ime/text/TextInputManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/key/KeyData.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/key/KeyView.kt

This PR adds an general option for `FlorisKeyData` to have an `shift` override `KeyData` attached to it, so an alternate key code can be shown when caps is active. Colemak and Dvoark layouts have been updated to take advantage of this new feature.
https://user-images.githubusercontent.com/19412843/110681935-a66dcf00-81da-11eb-91f9-07bacca7cdbe.mp4
---
Closes #145

Add option for an alternate key code when caps state is active

---

README.md
app/build.gradle.kts
app/src/main/java/dev/patrickgold/florisboard/ime/core/FlorisActivity.kt
app/src/main/java/dev/patrickgold/florisboard/ime/dictionary/DictionaryManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/dictionary/Flictionary.kt
app/src/main/java/dev/patrickgold/florisboard/ime/extension/Asset.kt
app/src/main/java/dev/patrickgold/florisboard/ime/extension/AssetManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/extension/AssetRef.kt
app/src/main/java/dev/patrickgold/florisboard/ime/extension/AssetSource.kt
app/src/main/java/dev/patrickgold/florisboard/ime/extension/ExternalContentUtils.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/TextInputManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/layout/LayoutManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/theme/ThemeManager.kt
app/src/main/java/dev/patrickgold/florisboard/settings/ThemeEditorActivity.kt
app/src/main/java/dev/patrickgold/florisboard/settings/ThemeManagerActivity.kt
app/src/main/java/dev/patrickgold/florisboard/settings/components/ThemeSelectorPreference.kt
app/src/main/res/drawable/ic_share.xml
app/src/main/res/layout/theme_editor_activity.xml
app/src/main/res/layout/theme_editor_meta_dialog.xml
app/src/main/res/layout/theme_manager_activity.xml
app/src/main/res/values/strings.xml

This PR adds the ability to import/export json theme files from/to the local file system by using the Android `GET_CONTENT` and ~`OPEN_DOCUMENT`~ `CREATE_DOCUMENT` actions. Note that the file selection UI is device/system dependent and can not be influenced by FlorisBoard. If the theme import/export functionality works well on all devices I will adopt this also to other areas of FlorisBoard, especially though dictionaries and layout json files.
Closes #93 
---
The theme editor now does not jump to the top when opening an attribute dialog.
Closes #379 
---
Other non-user relevant changes:
- Switched from [michaelbull/kotlin-result](https://github.com/michaelbull/kotlin-result) to the in-built Kotlin Result type
- Add internal `FlorisActivity`, which provides several useful utilities used …

Add theme import/export / Fix theme editor jumping to top

---

app/src/main/java/dev/patrickgold/florisboard/ime/core/InputView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/KeyboardView.kt

This PR is an attempt to improve the symbols key and font sizing when the number row in the character layout is activated. The new key sizing calculation is now similar to Gboard's and thus the font-size bug is minimized and almost not noticeable anymore. Open to suggestions though if the new sizing method should be improved and tweaked a bit, as it now looks a bit different than before.
https://user-images.githubusercontent.com/19412843/111925616-efab0200-8aa9-11eb-83f5-d6892c570521.mp4
https://user-images.githubusercontent.com/19412843/111925622-f3d71f80-8aa9-11eb-9ce3-d5e15c0119ef.mp4
Closes #203 because there's no need to set different font sizes anymore as the bug's effect has been minimized and is now almost unnoticeable.

Rework symbols sizing when number row is enabled

---

app/src/main/java/dev/patrickgold/florisboard/ime/clip/FlorisClipboardManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/clip/provider/FlorisDatabase.kt

Essentially I forgot to change the mimetype to plaintext when copying html, which causes #481
Somewhat unrelated, but I also switched to using a static array for the plaintext mimetype array. This way, every time a plaintext item is added, it doesn't allocate a brand new array.
Fixes #481

Fix for #481

---

app/src/main/java/dev/patrickgold/florisboard/ime/clip/FlorisClipboardManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/clip/provider/FlorisDatabase.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/PrefHelper.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/TextInputManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/smartbar/CandidateView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/smartbar/SmartbarView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/theme/ThemeValue.kt
app/src/main/res/layout/smartbar.xml
app/src/main/res/values/arrays.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml
app/src/main/res/xml/prefs_typing.xml

This PR reworks the UI of both the suggestions bar and also integrates the clipboard suggestions way better, thus allowing for a better suggestions experience. Note, that this PR does not fix any problems/crashes in the backend nor does it update or add new languages, these will come in future patches.
In detail, this has changed:
- The suggestions can now be displayed in three display modes: `Classic`, `Dynamic` and `Dynamic Scrollable`. Defaults to `Dynamic Scrollable`. This allows for a better customization and also more than 3 entries can be shown when using one of the dynamic options. (Settings > Typing > Suggestions display mode)
- The clipboard paste suggestion is now fully integrated into the suggestion view and will not clear as soon as you start typing, thus improving the …

Suggestions frontend rework

---

app/src/main/java/dev/patrickgold/florisboard/ime/popup/PopupManager.kt

This PR fixes the popup width in landscape mode (the width is now synced with the key view width) and additionally fixes a few bugs.
Portrait (unchanged) | Landscape
---|---
---
Closes #504 
Closes #505 
Closes #417

Adjust popups in landscape mode

---

app/src/main/assets/ime/config.json
app/src/main/assets/ime/text/characters/ipa.json
app/src/main/assets/ime/text/symbols/ipa.json
app/src/main/assets/ime/text/symbols2/ipa.json

In this PR I want to resolve #558. I did not implement the scheme I proposed, because I realized neither are intuitive (for example, it is unintuitive to find ɱ at the extension of f rather than m).
Not all symbols are mapped yet, work in progress. Characters denoting length, tones, stress,... are not mapped.

Add IPA keyboard layout

---

app/src/main/java/dev/patrickgold/florisboard/ime/popup/PopupManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/key/KeyView.kt
app/src/main/res/values/strings_dont_translate.xml

This PR adds support for proper display of [Combining Diacritical Marks](https://en.wikipedia.org/wiki/Combining_Diacritical_Marks) by adding a dotted circle as the base character while rendered on a key. Done to support keyboard layouts like the IPA (#560).

Add support for proper display of Combining Diacritical Marks

---

app/src/main/assets/ime/text/characters/extended_popups/fa.json

With this rearrange, when Accent is prioritized in hinted symbols, آ is the first option in the popup.
آ is one of the most used alphabets in Persian language.

Improve Persian popup (آ)

---

app/src/main/java/dev/patrickgold/florisboard/ime/core/EditorInstance.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/TextInputManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/gestures/GlideTypingManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/key/KeyView.kt

Fixes #581
Fixes #595
Fixes #604
@X-yl I've investigated into several glide suggestion issues and now changed some parts of the glide suggestion logic in the TextInputManager. Most importantly, I've eliminated the `hackyGlideSuggestionSkip` variable, because it was indeed very hacky :) When a glide word is now typed in, the phantom space flag is purposely not set, this way we can use the suggestion click logic without injecting some extra logic for glide typing. Furthermore, when manual typing in a letter after a glided word, a space is now set (except for characters like !?. etc.). The delete word feature now also resets when either clicking on a provided suggestion or when manual typing in a letter.
Could you check if I didn't accidentally remove a useful feature/functionality for the …

Fix glide logic in TextInputManager

---

app/src/main/java/dev/patrickgold/florisboard/debug/LogTopic.kt
app/src/main/java/dev/patrickgold/florisboard/ime/clip/ClipboardHistoryItemAdapter.kt
app/src/main/java/dev/patrickgold/florisboard/ime/clip/ClipboardInputManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/clip/FlorisClipboardManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/clip/provider/FileStorage.kt
app/src/main/java/dev/patrickgold/florisboard/ime/clip/provider/FlorisContentProvider.kt
app/src/main/java/dev/patrickgold/florisboard/ime/clip/provider/FlorisDatabase.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/EditorInstance.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/FlorisBoard.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/InputEventDispatcher.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/PrefHelper.kt
app/src/main/java/dev/patrickgold/florisboard/ime/media/MediaInputManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/TextInputManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/gestures/GlideTypingManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/KeyboardView.kt
app/src/main/java/dev/patrickgold/florisboard/util/summarize_utils.kt

This PR is an initial attempt at reducing the memory strain and improving the codebase. This PR alone will not introduce noticeable changes for the crashes (I think). You are of course free to try the debug APK out and see if anything regarding the OOM issues have changed. Note that this PR assumes you have glide typing and suggestions disabled (will be addressed by future PRs).
During inspections of memory allocations, a few things could be seen by me:
- The average memory consumption over a larger timeframe is increasing very slowly, which means in general the GC is able to pick up and remove unused objects and the number of memory leaks is low.
- When typing a lot in a relatively short timeframe, a lot of memory allocations are done, which leads to enormous spikes in memory usage. This …

OutOfMemory: Fix 1

---

.github/ISSUE_TEMPLATE/bug_report.md

Make everything use the same number of placeholder-periods (3). Also use "…" instead of three ".". It looks stupid in monospace, but it's nice in a regular font and is less annoying to delete.

Improve bug_report.md

---

.github/ISSUE_TEMPLATE/crash_report.md

Make everything use the same number of placeholder-periods (3). Also use "…" instead of three ".". It looks stupid in monospace, but it's nice in a regular font and is less annoying to delete, especially when using a phone.

Improve crash_report.md

---

app/src/main/java/dev/patrickgold/florisboard/ime/core/FlorisBoard.kt
app/src/main/java/dev/patrickgold/florisboard/settings/fragments/HomeFragment.kt
app/src/main/java/dev/patrickgold/florisboard/setup/EnableImeFragment.kt
app/src/main/java/dev/patrickgold/florisboard/setup/InputMethodChangedReceiver.kt
app/src/main/java/dev/patrickgold/florisboard/setup/MakeDefaultFragment.kt
app/src/main/java/dev/patrickgold/florisboard/util/ime_utils.kt

I did two changes in this PR:
1. Move the functions `checkIfImeIsEnabled` and `checkIfImeIsSelected` to a util class to reduce the huge size of the FlorisBoard class a bit
2. Get the result for a selection in the input method picker via a broadcast receiver instead of fetching it multiple times with random time delays

Improve ime activation

---

app/src/main/java/dev/patrickgold/florisboard/ime/media/emoji/EmojiKey.kt
app/src/main/java/dev/patrickgold/florisboard/ime/media/emoji/EmojiKeyAdapter.kt
app/src/main/java/dev/patrickgold/florisboard/ime/media/emoji/EmojiKeyData.kt
app/src/main/java/dev/patrickgold/florisboard/ime/media/emoji/EmojiKeyView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/media/emoji/EmojiKeyboardView.kt

This PR decreases memory usage by using a `RecyclerView` to recycle `EmojiKeyView`s instead of creating one for each emoji. This reduces memory usage by about 15-20% when suggestions and glide typing are disabled (in my somewhat limited short tests)
Let me know if you'd like me to make any changes.
Related: #677

Recycle EmojiKeyViews to reduce memory usage

---

app/src/main/java/dev/patrickgold/florisboard/ime/core/FlorisBoard.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/InputView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/PrefHelper.kt
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/prefs_advanced.xml

This PR adds a little overlay display in the top-right corner to show the heap memory usage. Useful for watching how the heap memory size grows and potentially find out what actions leave memory behind what is not de-allocated anymore. Note: the shown memory is only the heap, the native memory usage may be bigger than this and is not included. As most of the OOM errors occur due to a full heap though and it is easier to measure the heap size than the native size, the devtools currently only show the heap size. Defaults to disabled. To enable, go to Settings > Advanced > Enable debug mode > Show heap memory stats
Related #677
---

Add devtool overlay for heap memory usage

---

app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboard.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboardView.kt

Fix font size multiplier not applying since the layout rework in #734 (v0.3.11-beta02).
Additionally also scale the drawables based on the text. Closes #540.

Fix font size multiplier and also scale drawables

---

app/src/main/java/dev/patrickgold/florisboard/ime/text/gestures/StatisticalGlideTypingClassifier.kt

Noticed this issue while testing glide typing. If longestSide is ever zero, as sometimes happens because the dictionary contains "words" like "yyy" and "ggg", it causes NaN issues.

Make normalizeBoxSide have a non-zero minimum longestSide

---

app/src/main/java/dev/patrickgold/florisboard/ime/text/TextInputManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/gestures/GlideTypingManager.kt

No idea how I didn't notice it before but after glide typing a word, the suggestions are immediately replaced with the regular suggestions instead of showing the glide typing suggestions.
Another issue I noticded is that somewhat redundantly, the committed word shows as the first suggesion. I changed it to show the second best guess instead.

Stop glide suggestions disappearing and remove the redundant first suggestion

---

app/src/main/assets/ime/config.json
app/src/main/assets/ime/text/characters/bone.json
app/src/main/assets/ime/text/characters/extended_popups/de-DE-neobone.json
app/src/main/assets/ime/text/characters/mod/neo2.json
app/src/main/assets/ime/text/characters/neo2.json
app/src/main/assets/ime/text/numeric/row/neo2.json
app/src/main/assets/ime/text/symbols/mod/neo2.json
app/src/main/assets/ime/text/symbols/neo2.json
app/src/main/java/dev/patrickgold/florisboard/ime/text/layout/LayoutManager.kt
app/src/main/java/dev/patrickgold/florisboard/util/LocaleUtils.kt

Initial attempt at Neo2 / Bone layout
* For now, only layers 1, 2 and 3 are supported.
* Layer 2 is reachable via caps, apart from number row, comma and full stop (which I think are easier to use if not affected by caps). Instead, the relevant characters are added as popups.
* Layer 3 is set up as main popup, apart from number row, where
  a) due to existing number_row layout the main popup is already set
  b) the characters apart from the Euro sign are not used very often
The overall layout is kept as much as possible, with the following
exceptions:
* The number row contains only numbers to support the built-in number_row layout. The minus sign is moved to the lowest character row, while circumflex and grave accents are not included.
* To not overcrowd the layout and have the same number …

Neo2 layout

---

app/src/main/java/dev/patrickgold/florisboard/ime/core/Preferences.kt
app/src/main/java/dev/patrickgold/florisboard/ime/media/emoji/EmojiKeyView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/popup/PopupManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/popup/PopupSet.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/key/KeyHintConfiguration.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/TextKey.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboardView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/layout/LayoutManager.kt
app/src/main/res/values-de/strings.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/prefs_keyboard.xml

As discussed, I extracted my proposal for adding hints to the character layout in a more general fashion into a separate PR.
To allow symbol layouts with the same or more rows as the character
layout to be hinted more consistently, the hinting of the numeric row
is split from the rest of the symbol layout.
The numeric row hinting is always done in the first row. If the numeric
row is actually enabled, no additional hints will be shown (as hints
are only added to character type keys).
The symbol hinting is now bottom-aligned: hints from the last symbol
row are shown in the last character row.
Overall, only keys matching the expected type (numeric for numeric
row, character elsewhere) are iterated over. This allows also the
bottom row with the layout switch keys to be hinted.
Closes #618

Merge hints more flexibly

---

app/src/main/java/dev/patrickgold/florisboard/ime/text/gestures/StatisticalGlideTypingClassifier.kt

Closes #854.
This issue was that previously I assumed if the subtype is the same, the layout is the same. However, it is possible for the layout to change without the subtype changing, such as when enabling or disabling the number row. This change forces the pruner to be reinitialized if the previous layout is different.

Reinitialize pruner when layout changes

---

app/build.gradle.kts
app/src/main/AndroidManifest.xml
app/src/main/java/dev/patrickgold/florisboard/ime/core/FlorisBoard.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/InputView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/Preferences.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/smartbar/SmartbarView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/theme/ThemeManager.kt
app/src/main/java/dev/patrickgold/florisboard/settings/fragments/TypingInnerFragment.kt
app/src/main/res/drawable/chip_background.xml
app/src/main/res/layout/smartbar.xml
app/src/main/res/values/dimens.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml-v30/method.xml
app/src/main/res/xml/prefs_typing.xml

This PR is a working draft to add support for Android 11's Autofill API. Inline-suggestions works well in "normal" apps like Twitter but bugs out a bit in Firefox (Gboard bugs out too though so not 100% sure if I can do something against this). Closes #163.
Additionally the Language&Input settings bug has also finally been resolved by me (frickin `https` instead of the (sadly) correct `http` in the android schema tag was the issue in `method.xml`). Closes #366. Closes #890.

Add support for Android 11's Autofill API

---

app/src/main/assets/ime/text/characters/extended_popups/el.json

This pr fixes a recently introduced minor issue with the order of popups for letters "ι" and "υ" in greek layout. I tried it locally and it works as expected. Closes #912

Fix the default popup for some letters

---

app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/TextKey.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/layout/LayoutManager.kt

The merge of the hints depends on the underlying main key. Especially, hints should only be shown for character keys, and if the hint is identical to the main key, it should not be added at all. Since the actual main key is only evaluated on demand with TextKey#compute, all corresponding hint merge logic needs to be moved there too.
Closes #872

fix hint merge logic (#872)

---

app/src/main/java/dev/patrickgold/florisboard/ime/core/EditorInstance.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/FlorisBoard.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/InputEventDispatcher.kt
app/src/main/java/dev/patrickgold/florisboard/ime/popup/PopupManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/gestures/SwipeGesture.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyData.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboardView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/view/Pointer.kt

This PR introduces a new touch logic and support for multiple pointers on screen as well. This is an effort to improve the code base for adding additional gestures and to fix gestures which require two pointers at once (shift + space bar and shift + arrow keys).
Closes #871
Closes #932

Introduce new touch logic to TextKeyboardView

---

app/src/main/java/dev/patrickgold/florisboard/ime/core/FlorisBoard.kt

The `composers[composerNames.indexOf(activeSubtype.composerName)]` was always a bad idea and I knew it when I wrote it, but I thought "it's stupid but it's probably going to move to a better place anyways and for now it works" so I left it.
Except it doesn't work.
The `composers` list is unsorted, and the `composerNames` list is sorted, so their order is the same by pure chance in the current state of Florisboard, but that line still requires fixing before adding more composers. Otherwise this will happen.
This commit fixes it by adding a map to read the current composer from its name without sorting being a problem.
(Also it uses the constant Appender.name (that is already available for other purposes) rather than hardcoding "appender" when forcing the position of that composer to the …

Fix getting composer from name

---

app/src/main/java/dev/patrickgold/florisboard/ime/clip/ClipboardHistoryItemAdapter.kt
app/src/main/java/dev/patrickgold/florisboard/ime/clip/FlorisClipboardManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/FlorisBoard.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/Preferences.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/gestures/StatisticalGlideTypingClassifier.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboardView.kt
app/src/main/res/values/strings.xml
app/src/main/res/xml/prefs_gestures.xml

Firstly I just wanted to make all the old clipboard code I wrote which used `Executor` and `Handler` use Kotlin coroutines, to make it consistent with the rest of the project.
I also have improved bitmap loading in the clipboard manager a lot -- loading smaller samples in the preview and preventing jerking while the images are loading. Scrolling should be much smoother. 
I have also taken Etienne's advice and cached the ideal word lengths, this should be a decent performance improvement. 
Finally I wanted to make the glide trail fade based on time, not based on how far the pointer travels. It's a much needed bit of polish that makes glide typing look much smoother, while also getting rid of the fairly pointless max length preference.

Code cleanup + some polish

---

app/src/main/assets/ime/text/characters/extended_popups/tr.json
app/src/main/assets/ime/text/characters/turkish_f.json
app/src/main/assets/ime/text/characters/turkish_q.json
app/src/main/java/dev/patrickgold/florisboard/common/StringBuilder.kt
app/src/main/java/dev/patrickgold/florisboard/ime/clip/ClipboardInputManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/InputEventDispatcher.kt
app/src/main/java/dev/patrickgold/florisboard/ime/keyboard/ComputingEvaluator.kt
app/src/main/java/dev/patrickgold/florisboard/ime/keyboard/Key.kt
app/src/main/java/dev/patrickgold/florisboard/ime/keyboard/KeyData.kt
app/src/main/java/dev/patrickgold/florisboard/ime/media/emoji/EmojiKey.kt
app/src/main/java/dev/patrickgold/florisboard/ime/media/emoji/EmojiKeyData.kt
app/src/main/java/dev/patrickgold/florisboard/ime/media/emoji/EmojiKeyView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/media/emoji/EmojiLayoutData.kt
app/src/main/java/dev/patrickgold/florisboard/ime/popup/PopupExtension.kt
app/src/main/java/dev/patrickgold/florisboard/ime/popup/PopupLayerView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/popup/PopupManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/popup/PopupSet.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/TextInputManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/key/CurrencySet.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/TextKey.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyData.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboardView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/layout/Layout.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/layout/LayoutManager.kt
app/src/main/java/dev/patrickgold/florisboard/res/Asset.kt
app/src/main/java/dev/patrickgold/florisboard/res/AssetManager.kt
app/src/main/java/dev/patrickgold/florisboard/settings/ThemeManagerActivity.kt

This PR reworks the KeyData logic so popups can also fully use variation and case selectors. This is required to fully implement the Turkish layout, but also may be needed in the future. This rework also allows for a more general use of the KeyData interface and unifies the text and emoji data base (kinda).
Additionally fixes #1045 and fixes #1089

Keyboard data logic rework

---

app/src/main/java/dev/patrickgold/florisboard/ime/text/gestures/SwipeGesture.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboardView.kt
app/src/main/res/values/dimens.xml

This PR attempts to fix the several reported bug that gestures don't activate on some devices. The velocity detection was based on Pixels instead of Display-Independent-Pixels, thus the screen density had a big impact on if a gesture could be detected or not. Now, the velocity is converted to DiP before checking, which should fix the gesture detection bugs.
Closes #1086 
Closes #972
Closes #549

Fix gesture logic to adapt to screens with different screen densities

---

app/src/main/java/dev/patrickgold/florisboard/ime/clip/FlorisClipboardManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/clip/provider/FlorisDatabase.kt

Looks like I forgot to clone images when the internal clipboard is off but the clipboard history is still on. We have to own the items in the clipboard history since authorization to read them is temporary.
Fixes #1124.

Make sure to clone images in clipboard history

---

app/src/main/assets/ime/text/characters/extended_popups/tr.json

+ Removed unnecessary letters that Turkish language doesn't have.
+ Edited domain extensions for correct local usage.
- Still have no idea about how to assign lower case "i" to upper case "İ" and lower case "ı" to upper case "I"
Closes #882

Remove popups not related to Turkish

---

app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboardView.kt

Closes #1100 which affected several non-Latin keyboards.
@GoRaN909 Could you test out the change if it works with your Kurdish layouts? Thanks!

Fix 5+1 keyboard layout bug

---

app/src/main/assets/ime/text/characters/extended_popups/ar.json

This commit makes the most common popups the main ones which should
allow Arabic sub-layout users to use FlorisBoard's smart popup feature.
Closes #1087

Adjust popups for Arabic main forms and remove prebaked numbers.

---

app/src/main/java/dev/patrickgold/florisboard/debug/LogTopic.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/EditorInstance.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/FlorisBoard.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/TextProcessor.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/TextInputManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboardView.kt
app/src/main/java/dev/patrickgold/florisboard/settings/UdmActivity.kt
app/src/test/java/dev/patrickgold/florisboard/ime/core/EditorInstanceTest.kt
app/src/test/java/dev/patrickgold/florisboard/ime/core/TextProcessorTest.kt

This PR is a rework for the cached input logic, text processing & word detection logic. Additionally fixes the fully bugged whole-word deletion and current word deletion swipe.
- Fix crash when swiping:  
Closes #1130  
Closes #1076  
Closes #1065  
Closes #1014  
- Fix inconsistent selection:
Closes #546  
Closes #547
- Deletion does not work:
Closes #1072  
Will be fixed at a later stage: #548

Rework EditorInstance cached input and word detection logic

---

app/src/main/assets/ime/text/characters/extended_popups/ca.json

Let me explain this. Catalan people like me also speak Spanish, and we usually use both languages at the same time while typing, so it comes very handy to have ñ on the Catalan keyboard (even though it's not on the alphabet). Keyboards like GBoard already do this.
Thanks!

Add ñ as popup on catalan layout

---

app/src/main/assets/ime/keyboard/org.florisboard.localization/popupMappings/ro.json

* The key hints are now the default popup keys. The old behavior was very confusing.
* Improved the URI TLD list:
* `.ro` is now to the right of `.com`
* added `.eu`
* removed the US `.edu`
* Updated the Romanian layout to include all possible punctuation marks recognized by the Romanian Academy.
EDIT: Fixed uppercase letters.

Update the Romanian layout

---

app/src/main/AndroidManifest.xml
app/src/main/res/xml-v31/backup_rules.xml
app/src/main/res/xml/backup_rules.xml

Add manifest entry for allowing encrypted auto backup, either via Google's auto backup service on GMS devices or via Seedvault on AOSP-based devices.
Included files in auto-backups:
- All app preferences: `jetpref_datastore/*`
- Custom layouts, dictionaries (spelling) and custom themes: `files/ime/*`
Excluded files from auto-backup:
- Clipboard history, pins, images stored in the clipboard history
- Generated crash reports (which have not been viewed in the crash report screen)
- Floris user dictionary
---
Closes #272 
Closes #1324

Enable encrypted backup for app data (#272, #1324)

---

app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/characters/urdu_phonetic.json

2 fixes for wrong layout in the Urdu phonetic keyboard. One was a wrong(duplicate) HTML code causing 2 different keys to output the same character. The other was a wrong label on a key resulting in 1 key label appearing twice and giving 2 different outputs.

Update Urdu phonetic layout

---

app/src/main/java/dev/patrickgold/florisboard/ime/core/EditorInstance.kt

Fix #1232 
Fix #1468 
Fix #1554 
Fix #1576 
Added an additional check for `ic.getSelectedText(0)` being `null`

fix: add check for null selectedText when performing a copy

---

app/src/main/assets/ime/keyboard/org.florisboard.localization/popupMappings/ar.json
app/src/main/assets/ime/keyboard/org.florisboard.localization/popupMappings/fa.json
app/src/main/assets/ime/keyboard/org.florisboard.localization/popupMappings/ur-PK.json

Fix Arabic diacritics showing empty popups on long press, Also changed the default top-level-domain `TLD` to saudi arabia `SA` for arabic popup mapping and `PK` for Urdu language.
This PR is fixes #1679

Fix TLDs of Arabic and Urdu-Phonetic

---

app/src/main/assets/ime/keyboard/org.florisboard.currencysets/extension.json
app/src/main/assets/ime/keyboard/org.florisboard.layouts/extension.json
app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/characters/eastern_armenian.json
app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/characters/western_armenian.json
app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/charactersMod/armenian.json
app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/symbols/armenian.json
app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/symbolsMod/armenian.json
app/src/main/assets/ime/keyboard/org.florisboard.localization/extension.json
app/src/main/assets/ime/keyboard/org.florisboard.localization/popupMappings/hy.json

Thank you so much for your work on this project.
I've added the Armenian Dram currency set, layouts for Eastern and Western Armenian, Armenian popup mappings, and Eastern and Western Armenian subtype presets.
Closes #492

Add Armenian keyboard layouts

---

app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/TextKey.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboardLayout.kt

This PR aims to improve the telpad input UI. Two simple changes are done:
1. Remove popups from phone layouts, in accordance to the removal from numeric in #1044
2. Add alphabetic characters to phone digits (Fixes #355):

Improve telpad UI (alphabetic letters and popups)

---

app/src/main/assets/ime/keyboard/org.florisboard.layouts/extension.json
app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/characters/persian2.json
app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/charactersMod/persian2.json
app/src/main/assets/ime/keyboard/org.florisboard.localization/extension.json
app/src/main/assets/ime/keyboard/org.florisboard.localization/popupMappings/fa2.json

Simply added new layout based on Swiftkey keyboard Persian layout. New popups too (I don't know it will work or not)

Adding new layout for Persian

---

app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/characters/eastern_armenian.json
app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/characters/western_armenian.json

The Eastern and Western Armenian layouts had a duplicate letter դ instead of the letter փ.  This PR fixes that issue.

Fix Armenian layouts duplicate letter

---

app/src/main/assets/ime/keyboard/org.florisboard.localization/extension.json
app/src/main/assets/ime/keyboard/org.florisboard.localization/popupMappings/uk-cyr-ext.json
app/src/main/assets/ime/keyboard/org.florisboard.localization/popupMappings/uk.json

Hello!
First of all, thank you for your work on the keyboard, it's awesome!
Now, about the PR itself. This PR somewhat improves the Ukrainian popup mappings making it a bit easier to use, especially for people also using the minority languages in parallel (Crimean Tatar, Russian, Bulgarian, Belorussian etc).
Particularly, I've done two changes:
* added some missing letters and useful symbols to the core Ukrainian layout (`uk.json`)
* created a new extended layout with extra letters for the Cyrillic-based minority languages (`uk-cyr-ext.json`)
Hope it works well, tell me if I need to make some changes.
Good luck with the new versions of the app and thank you again!

Ukrainian popup mappings improvements

---

app/build.gradle.kts
app/src/main/kotlin/dev/patrickgold/florisboard/app/Routes.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/devtools/DevtoolsScreen.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/devtools/ExportDebugLogScreen.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/keyboard/KeyboardManager.kt
app/src/main/kotlin/dev/patrickgold/florisboard/lib/FlorisLocale.kt
app/src/main/kotlin/dev/patrickgold/florisboard/lib/crashutility/CrashDialogActivity.kt
app/src/main/kotlin/dev/patrickgold/florisboard/lib/devtools/Devtools.kt
app/src/main/kotlin/dev/patrickgold/florisboard/lib/devtools/Flog.kt
app/src/main/kotlin/dev/patrickgold/florisboard/lib/kotlin/Strings.kt
app/src/main/kotlin/dev/patrickgold/florisboard/lib/util/TimeUtils.kt
app/src/main/kotlin/dev/patrickgold/florisboard/lib/util/UnitUtils.kt
app/src/main/res/values/strings_dont_translate.xml

This PR adds a debug log feature, which allows to export (copy to clipboard) the full debug log (header + Logcat) via the devtools. The main motivation behind this change is to be able to have more detailed logs available in case something goes wrong and to improve the bug finding workflow by having more details in the crash section.
To be able to better identify debug versions and with that commit they were built, the version name suffix for this track now looks like this: `-debug-abcd123`, where `abcd123` is the short git hash of the build commit (first 7 chars by default). In the debug and crash log the full commit hash is included for exact identification.
The crash log generation has changed a bit, to include a bit more details (in the detailed info tag). This allows me to identify …

Improve devtools and crash log / Add debug log

---

app/src/main/assets/ime/keyboard/org.florisboard.localization/popupMappings/tr.json

So, I tried to address this, but i couldn't get "î" to also show with caps lock. So I'm hoping for a little tip😃
Closes #1962

Add circumflex popups to Turkish layout (#1962)

---

app/src/main/kotlin/dev/patrickgold/florisboard/ime/editor/AbstractEditorInstance.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/editor/EditorInstance.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/composing/Composer.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/composing/HangulUnicode.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/composing/KanaUnicode.kt

The current composer implementation does not allow for characters with multiple code points to be inserted. This issue has been detected due to tests with the `MultiTextKey` in #1984.
This PR reworks this and now in general multiple code points are supported (especially for the default `Appender` composer), however some specific composers may internally still use single Java char notation.

Fix composer not allowing multiple code points

---

app/src/main/assets/ime/keyboard/org.florisboard.localization/popupMappings/el.json

So, I gave this a shot, but it turned out I didn't know how to handle more than one popup with `case_selector`. Thus, I'm once again looking for an advice😁
Closes #1981

Fix uppercase Greek vowels popups

---

.github/workflows/android.yml

This should fix some ci warnings. Also added gradle/wrapper-validation-action, I guess it's good to have. I don't know if you prefer another java distribution, if so, let me know.

Update workflows dependencies

---

LANGUAGEPACKS-CHINESE.md
LANGUAGEPACKS.md
app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/symbolsMod/cjk.json
app/src/main/assets/ime/languagepack/org.florisboard.hanshapebasedbasicpack/extension.json
app/src/main/kotlin/dev/patrickgold/florisboard/FlorisImeService.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/devtools/DevtoolsOverlay.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/editor/AbstractEditorInstance.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/editor/EditorInstance.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/keyboard/KeyboardManager.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/nlp/NlpManager.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/nlp/NlpProviders.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/nlp/han/HanShapeBasedLanguageProvider.kt

This PR is based on #2054 and adds some quality-of-life updates for using the new subtype to type a mixture of Chinese and English text.
- Allowing committing raw input using Enter with CJK, and allowing the committed text to persist instead of being included in the composing range again. ~See below for caveat.~
- Reset suggestions when changing keyboard subtypes.
- ~Delegate NlpProvider to determine composing range when starting IME or moving cursor. Latin behavior remains considering the last word, and HanShapeBased only consider viable characters (lowercase letters for now, but may need to add support a different set for each input method).~ (already merged)
- Update: tracks the last commit position, and limits `HanShapeBasedLanguageProvider` to not compose beyond that position.
- …

Fixes to Chinese shape-based layout: mixed language support

---

app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/charactersMod/persian.json

There is a Kashida(code: 1600) key inside
the popup of Dot key(code: 46). The Kashida is
a very low use character in Persian writing, so
removing it from the main layout improves the
layout usability by increasing the width of the
Space-bar.

Remove redundant Kashida key in Persian layout

---

app/src/main/kotlin/dev/patrickgold/florisboard/ime/onehanded/OneHandedPanel.kt

Closes: #2173 The arrow-button now extends to the full width and height of the free space in one-handed mode.

Implement #2173

---

README.md
app/build.gradle.kts
app/src/main/kotlin/dev/patrickgold/florisboard/ime/theme/ThemeManager.kt
build.gradle.kts
gradle.properties
gradle/wrapper/gradle-wrapper.properties

This PR upgrades the target SDK to 34 to comply with Google's guidelines. Additionally we migrate to using non-transitive R-classes, other dependencies are upgraded and some minor cleanup is done.

Upgrade traget SDK to 34 and cleanup code base

---

app/src/main/assets/ime/keyboard/org.florisboard.localization/popupMappings/hu.json

In Hungarian we have a few letters with accents. I added the most frequently used ones as a `main` popup, so with Hungarian popup mapping the accented letters will be the default choices in the popups regardless of the symbols.
I took the frequency of letters from [this](https://golem.hu/tool/letter-frequency/) article.

Add main symbols to Hungarian localization based on letter frequency

---

app/src/main/kotlin/dev/patrickgold/florisboard/app/AppPrefs.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/keyboard/KeyboardScreen.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/keyboard/KeyboardManager.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/smartbar/IncognitoDisplayMode.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/smartbar/Smartbar.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/TextInputLayout.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyData.kt
app/src/main/res/values/strings.xml

Smartbar enhancements

---

app/src/main/assets/ime/keyboard/org.florisboard.layouts/extension.json
app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/characters/diktor.json
app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/charactersMod/diktor.json

Diktor is an ergonomic layout for Russian language. (Russian analog of Dvorak)
https://olegp.name/software/diktor-keyboard-layout/geocities/
https://github.com/mshkrebtan/diktor
(I created this merge request because i'm so bored to inject diktor.json in every new update)

Add Diktor layout

---

app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/symbols/cjk.json
app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/symbols2/cjk.json
app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/symbols2Mod/cjk.json
app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/symbolsMod/cjk.json
app/src/main/assets/ime/keyboard/org.florisboard.localization/extension.json
app/src/main/assets/ime/keyboard/org.florisboard.localization/popupMappings/cjk.json

- fix full-width comma
- add () to first symbol screen popups
- merge postal sign with # popups
- add = to + popup
- add full-width = to half-width popup
- fix half-width <> and single guillemets ‹›
- add check mark to square root symbol popup
- Add [] to popups
- Add pinyin characters in popup mapping
TODO:
- Consider making the full- and half-width toggle instead have three states. Add a state that is full-width for punctuation but half-width for other characters.
- Actually test

CJK keyboard adjustments for better Chinese input convenience

---

app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/characters/armenian_alt_phonetic.json
app/src/main/assets/ime/keyboard/org.florisboard.localization/popupMappings/hy-am.json

Thank you on your amazing work on this project!
The following is the alternative phonetic layout which is the most commonly used layout here in Armenia. This is also the layout Gboard uses by default on android phones.

Added Armenian alternative phonetic layout

---

app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/characters/udmurt_compact.json
app/src/main/assets/ime/keyboard/org.florisboard.localization/extension.json

There are some issues with the Udmurt subtype that this pull request tries to fix:
- When selecting the Udmurt subtype preset, Florisboard does not find and select the `udm` popup mapping.
- The key `з` stays lowercase, even when the keyboard is shifted/caps-locked.
- Popups stay lowercase, even when the keyboard is shifted/caps-locked.
- When you try to fix this bullet point, some popup characters appear twice. (This pull request also fixes that.)
Fixes #2441

Change files of Udmurt subtype

---

app/src/main/kotlin/dev/patrickgold/florisboard/ime/keyboard/ComputingEvaluator.kt

The symbol for the backspace key on the keyboard was filled in instead of outlined. This was wrong since #2432, in which the wrong icon was introduced

fix backspace icon

---

.github/workflows/android.yml
.github/workflows/crowdin-upload.yml

This PR updates the Github Actions used in the `build` and `upload-to-crowdin` action to the latest (major) versions. This removes the dependency on Node.JS 16, which [was deprecated by GitHub](https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/). Therefore, there should not be [deprecation warnings](https://github.com/florisboard/florisboard/actions/runs/9943663479) in action runs anymore.

Update Github Actions

---

app/src/main/AndroidManifest.xml
app/src/main/kotlin/dev/patrickgold/florisboard/app/Routes.kt

Closes: #2526 
This PR replaces the animation that is played during settings navigation. Now it is the same as in the android settings.
In addition, predictive back was prepared with the `android:enableOnBackInvokedCallback="true"` manifest flag.

Switch to sliding navigation animation

---

app/src/main/kotlin/dev/patrickgold/florisboard/app/apptheme/Theme.kt
app/src/main/kotlin/dev/patrickgold/florisboard/lib/compose/FlorisScreen.kt

The system-navigation-bar color was adjusted so that it is usable on older API versions. Below is a comparison table showing the change. 
> [!NOTE]
> Even though the black navigation bar is probably not the cleanest solution, it is now much more usable. I also made sure not to use any deprecated functions in my implementation, which made the whole thing a bit more difficult and that's why I chose this solution
| API Level | Previously | Now |
|--------|--------|--------|
| 24 | ![Screenshot_20240816_002511](https://github.com/user-attachments/assets/a22a30dc-1d0d-4151-97d5-225af59180c8) | ![Screenshot_20240816_002404](https://github.com/user-attachments/assets/64aa48dc-8f06-4130-974c-22ac745cbb1b) |
| 26 | ![Screenshot_20240816_003138](https://github.com/user-attachments/assets/3a03cad7-65 …

Fix transparent navigation bar color on older api levels

---

README.md

fix addon store link pointing to incorrect url

---

app/build.gradle.kts
gradle.properties

The version suffix is now encoded in `versionName` instead of being in a separate gradle.properties value to ease handling in bash scripts

Rework version name handling in Gradle

---

lib/native/src/main/rust/CMakeLists.txt

Fix needed for F-Droid build recipe to properly work as somehow the PATH env is not correctly set up in that process

Add hint to find_program for Rust discovery

---

lib/native/build.gradle.kts
lib/native/src/main/rust/CMakeLists.txt

Cargo.lock was accidentally cleaned every build time which caused rustc to rewrite the Cargo.lock file, now the lock file is only updated when the dependencies are updated with cargo.

Fix Rust Cargo.lock file getting rewritten during build

---

app/src/main/assets/ime/keyboard/org.florisboard.localization/popupMappings/sl-SI.json

This PR fixes a problem in Slovenian popup mapping. There was a trailing comma in the JSON file, which meant that the popup mapping could not be used.

Remove trailing comma to comply with the JSON spec

---

app/src/main/kotlin/dev/patrickgold/florisboard/app/devtools/ExportDebugLogScreen.kt
app/src/main/kotlin/dev/patrickgold/florisboard/lib/devtools/Devtools.kt
app/src/main/res/values/strings.xml

This PR adds a button that copies the debuglog already preformatted for github to the clipboard.
In addition the stringres for the ExportDebugLogScreen were added.

Localize debug log screen and add option for preformatted exporting

---

app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/advanced/BackupScreen.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/advanced/RestoreScreen.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/clipboard/ClipboardManager.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/clipboard/provider/ClipboardFileStorage.kt

This PR fixes the Clipboard History Checkbox in the backup and restore screens to better reflect the selection of the items. 
A new Composable `TriStateCheckboxListItem` was added. 
If nothing or not everything is selected, then everything is selected by pressing the checkbox. If all subitems are selected, everything is deselected by pressing the checkbox
This PR fixes a bug that was caused by adding clipboard media files that already existed. In addition, the clipboard history as well as the files are now reset correctly with erase and override.

Update clipboard backup and restore behavior

---

app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/TextInputLayout.kt

Closes #2573
Original behavior: Incognito icon stretches the box as mentioned by @kizaski
matchParentSize will resize the icon to fit the box.
Keeping requiredSize alongside matchParentSize will result in behavior as shown below

Fix incognito icon messing up landscape input height

---

app/src/main/kotlin/dev/patrickgold/florisboard/ime/keyboard/KeyboardManager.kt

Closes #2586
Closes #2587
This PR addresses both the issue that the utility key action pref was not observed and that subtype list changes did not properly propagate to the evaluator, causing the evaluate**() methods to be always 1 behind.

Fix utility key action not correctly applied

---

app/src/main/kotlin/dev/patrickgold/florisboard/app/AppPrefs.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/EnumDisplayEntries.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/media/MediaScreen.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/media/emoji/EmojiData.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/media/emoji/EmojiPaletteView.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/media/emoji/EmojiRecentlyUsedHelper.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/media/emoji/EmojiSuggestionProvider.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/media/emoji/EmojiSuggestionType.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/nlp/NlpManager.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/nlp/NlpProviders.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/nlp/SuggestionCandidate.kt
app/src/main/res/values/strings.xml

This PR is a major rework of the emoji suggestions, the main goal of this is to make the UX for configuring the emoji suggestions better and to improve behavior.
List of changes:
- Add separate toggle for enabling emoji suggestions.
- This now allows using emoji suggestions _independently_ of the normal typing suggestions being enabled/disabled
- Add trigger type option, allowing toggling between leading colon (`:emoji_name`) syntax inline word detection method
- Add toggle for allowing automatic updates of the emoji recently used history if an emoji suggestion is accepted. Defaults to true
- Add toggle allowing showing/hiding the emoji name below the suggested emoji in the Smartbar
- Allow configuring internal minimum query length and maximum candidate count parameters
- Fix emoji data …

Major rework of emoji suggestions

---

app/src/main/kotlin/dev/patrickgold/florisboard/app/AppPrefs.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/EnumDisplayEntries.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/media/MediaScreen.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/media/emoji/Emoji.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/media/emoji/EmojiHistory.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/media/emoji/EmojiPaletteView.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/media/emoji/EmojiSuggestionProvider.kt
app/src/main/kotlin/dev/patrickgold/florisboard/lib/compose/LazyGrid.kt
app/src/main/res/values/strings.xml

This PR's main goal is to fully rework the internal behavior of the emoji history and to add a few new fetaures. List of changes:
- Add ability to enable/disable emoji history (closes #1990)
- Add ability to pin emojis in emoji history (closes #2273)
- Add ability to manually reorder emojis in history (closes #1975)
- Fix emoji history update bug if items is max size (closes #2129)
- Rewrite emoji history logic and data class

Major rework of emoji history

---

app/src/main/kotlin/dev/patrickgold/florisboard/ime/media/emoji/Emoji.kt

This PR fixes a bug introduced in PR #2611, where equal emoji values but with differing emoji meta data (name, keywords) were not seen as the same.

Fix emojis with differing meta data not being seen as identical

---

app/build.gradle.kts
app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboardLayout.kt

This PR disables [compose strong skipping mode](https://developer.android.com/develop/ui/compose/performance/stability/strongskipping), which causes all sorts of state bugs in FlorisBoard. Long-term goal is to support strong-skipping, but for now keep it disabled.
Closes #2629

Disable compose strong skipping mode

---

app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/symbols/ipa.json

In the IPA symbols layout, the bracket "⟪" is incorrectly labeled as "⟩", and the bracket "⟧" is incorrectly labeled as "⟦".

Fix some labels in the IPA symbols layout

---

app/schemas/dev.patrickgold.florisboard.ime.clipboard.provider.ClipboardHistoryDatabase/3.json
app/schemas/dev.patrickgold.florisboard.ime.clipboard.provider.ClipboardHistoryDatabase/4.json
app/src/main/kotlin/dev/patrickgold/florisboard/ime/clipboard/provider/ClipboardDatabase.kt

This PR fixes the missing items in the clipboard database after updating to 0.4.2 by adding a migration (version 2 -> 3) to the clipboard database

Fix migration in clipboard database

---

app/src/main/assets/ime/keyboard/org.florisboard.localization/popupMappings/bn-BD.json

This pull request addresses an issue in the keyboard layout where the Bengali 'র‌্য' was incorrectly defined using Zero Width Non-Joiner (ZWNJ, U+200C) instead of Zero Width Joiner (ZWJ, U+200D).
Updated the layout to conform to the Unicode Standard, which specifies the use of ZWJ for forming 'র‌্য'.

Fix Bengali 'র‌্য' in Keyboard Layout to Use ZWJ (U+200D) as per Unicode Standard

---

app/src/main/kotlin/dev/patrickgold/florisboard/lib/FlorisLocale.kt

This pull request improves language handling by including Bengali (bn) in the list of languages without a capitalization concept. Bengali does not distinguish between uppercase and lowercase letters.

Add Bengali (bn) to non-capitalization languages

---

app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/localization/SubtypeEditorScreen.kt

| Before the change | After the change |
|--------|--------|
| ![signal-2025-01-08-163843](https://github.com/user-attachments/assets/f705a140-35bd-4ae6-8657-95bf79ffa896) | ![signal-2025-01-08-163843_004](https://github.com/user-attachments/assets/42f3baab-e618-4cfc-847d-91e980def272) |
|![signal-2025-01-08-164844](https://github.com/user-attachments/assets/d5515495-61c4-4f58-b53d-69ce078a4fff) | ![signal-2025-01-08-163843_003](https://github.com/user-attachments/assets/cd04dfa9-c08e-408e-a7f9-1598f3b6db77)|

Fix colors in add subtype screen and enhance subtype presets dialog

---

app/src/main/kotlin/dev/patrickgold/florisboard/lib/devtools/Devtools.kt

This PR adds two new information groups to the debug log. Installed theme extensions (can be expanded with more extension types in the future) and the currently selected and installed subtypes. These changes were made to create a better and more accurate environment for debugging bugs, and to better understand possible configuration-specific bugs.

Add subtypes and installed extensions to debug logs

---

app/src/main/kotlin/dev/patrickgold/florisboard/ime/clipboard/ClipboardInputLayout.kt

This Commit fixes a crash when opening the clipboard history with a theme which does not provide a sp size for the header or the clipboard item. The sp value is now saveTimes multiplied with 1f.
To reproduce the crash on a version without this commit, edit a theme so that it does not provide a sp size for the header or the clipboard item.
Many thanks to @akash0228 for identifying the issue.
Closes: #2720

Fix crash when opening clipboard history (#2720)

---

app/src/main/kotlin/dev/patrickgold/florisboard/ime/sheet/BottomSheetHostUi.kt

This commit fixes an issue where the BottomSheetContent was drawn behind the system navigation bar. To fix this issue, I applied the saveDrawingPadding Modifier to the AnimatedVisibility. There was a color problem on the system navigation bar, so I set the background color to SheetOutOfBoundsBgColorInactive. Now the system nav bar is colored the right way.

Fix BottomSheetContent drawing behind system nav bar

---

app/src/main/kotlin/dev/patrickgold/florisboard/FlorisImeService.kt

This commit fixes an issue where the voice ime was not possible to switch back to FlorisBoard, because the keyboard subtype was not specified.
Many thanks to @ElishaAz for pointing out the issue and providing a fix.
Closes: #2684

Fix switching back from voice ime (#2684)

---

app/src/main/kotlin/dev/patrickgold/florisboard/lib/crashutility/CrashDialogActivity.kt
app/src/main/res/layout/crash_dialog.xml
app/src/main/res/values/themes.xml

This commit fixes an issue where the text was rendered behind the top app bar in the crash dialog activity by removing the top app bar in the style and adding a top app bar in the layout XML.

Fix text being rendered behind the top app bar

---

app/src/main/kotlin/dev/patrickgold/florisboard/FlorisApplication.kt
app/src/main/kotlin/dev/patrickgold/florisboard/FlorisImeService.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/theme/WallpaperChangeReceiver.kt
app/src/main/kotlin/dev/patrickgold/florisboard/lib/compose/SystemUi.kt

Closes: #2746 
This PR updates the snygg material you color scheme cache on wallpaper change. As discussed in https://github.com/florisboard/florisboard/issues/2746#issuecomment-2680565699 this seems to fix the navigation bar color issue that occurred on updates to the wallpaper.

Update snygg dynamic color scheme on wallpaper change

---

app/src/main/kotlin/dev/patrickgold/florisboard/FlorisImeService.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/AppPrefs.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/EnumDisplayEntries.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/FlorisAppActivity.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/Routes.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/apptheme/Theme.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/HomeScreen.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/advanced/OtherScreen.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/clipboard/ClipboardScreen.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/typing/TypingScreen.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/clipboard/FlorisCopyToClipboardActivity.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/editor/EditorInstance.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/keyboard/KeyboardManager.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/nlp/NlpManager.kt
app/src/main/res/values/strings.xml

Closes: #2775 
Closes: #2771
This PR renames the advanced settings to App Settings to better reflect what they are doing.
It also removes the old settings migration rules.
> [!CAUTION]
> This PR is part of the 0.5 dev cycle and should only be merged if it has started.

Refactor Settings

---

app/src/main/kotlin/dev/patrickgold/florisboard/FlorisImeService.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/AppPrefs.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/EnumDisplayEntries.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/keyboard/KeyboardScreen.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/keyboard/ComputingEvaluator.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/keyboard/FlorisImeSizing.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/keyboard/KeyboardManager.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/onehanded/OneHandedMode.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/onehanded/OneHandedPanel.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/smartbar/quickaction/QuickAction.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/smartbar/quickaction/QuickActionArrangement.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/key/KeyCode.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyData.kt
app/src/main/res/values/strings.xml

The one-handed mode now remembers the position
where it was disabled and opens to this position
the next time it is activated.
Closes #2036

Rework one-handed mode.

---

app/src/main/AndroidManifest.xml
app/src/main/res/layout/crash_dialog.xml

The whole crash screen content is now scrollable
and the buttons to report or close the activity
were moved to a footer. To distinguish between
the log content and the general explanation, 
a horizontal divider was added.
Closes #726

Improve crash screen

---

app/src/main/assets/ime/theme/org.florisboard.themes/stylesheets/floris_day.json
app/src/main/assets/ime/theme/org.florisboard.themes/stylesheets/floris_day_borderless.json
app/src/main/assets/ime/theme/org.florisboard.themes/stylesheets/floris_night.json
app/src/main/assets/ime/theme/org.florisboard.themes/stylesheets/floris_night_borderless.json
app/src/main/assets/ime/theme/org.florisboard.themes/stylesheets/floris_pure_night.json
app/src/main/assets/ime/theme/org.florisboard.themes/stylesheets/floris_pure_night_borderless.json
app/src/main/kotlin/dev/patrickgold/florisboard/ime/core/SelectSubtypePanel.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/theme/FlorisImeThemeBaseStyle.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/theme/FlorisImeUi.kt
app/src/main/res/values/strings.xml
lib/snygg/src/main/kotlin/org/florisboard/lib/snygg/ui/SnyggListItem.kt

Fixes #2885 
The following changes are being made:
- Add element `subtype-panel-list`
- Add element `subtype-panel-list-item`
- Add element `subtype-panel-list-item-icon-leading`
- Add element `subtype-panel-list-item-text`
- Update default themes and base style regarding good default sizes/paddings
The list item style accepts most Snygg properties, `margin` may cause some layout issues if applied to the icon or text inner styles.
Screenshots:
| Floris Day       | Floris Night     |
|------------------|------------------|
| ![image](https://github.com/user-attachments/assets/672259ea-1bbe-442d-b823-1b500a136172) | ![image](https://github.com/user-attachments/assets/b6d7c139-3951-4b80-b590-c43b646145c8) |

Add SnyggListItem / Allow styling of subtype pnale list items

---

app/src/main/assets/ime/keyboard/org.florisboard.layouts/extension.json

The [armenian_alt_phonetic.json](https://github.com/florisboard/florisboard/commit/a7f8980d350aedaa6af26083e678fbca5b3d7833#diff-2b961f94cbb97e3bf1d5ec590214ff2fc568e200c8e701d73a4a5d075ef236c0) was configured (commit [a7f8980](https://github.com/florisboard/florisboard/commit/a7f8980d350aedaa6af26083e678fbca5b3d7833)) but wasn't properly added to extension.json, that's why it doesn't show up in the layout menu.
Thank you all for your hard work :)

Add Armenian layout to extension.json

---

app/src/main/kotlin/dev/patrickgold/florisboard/FlorisImeService.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/EnumDisplayEntries.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/theme/EditRuleDialog.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/input/InputShiftState.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/keyboard/KeyboardMode.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/popup/PopupUi.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/popup/PopupUiController.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboardLayout.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/theme/FlorisImeTheme.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/theme/FlorisImeThemeBaseStyle.kt
app/src/main/res/values/strings.xml
lib/snygg/src/main/kotlin/org/florisboard/lib/snygg/ui/SnyggUi.kt

This PR adds the `mode` attribute, which allows to further customize the theme based on the active mode.
The following attribute values are supported:
- `characters`
- `symbols`
- `symbols2`
- `numeric`
- `numeric_advanced`
- `phone`
- `phone2`
It can be applied to the following elements:
- `root`
- `window`
- `key`
- `key-hint`
- `key-popup-box`
- `key-popup-element`
- `key-popup-extended-indicator`

Add `mode` attribute to select element styles

---

app/src/main/assets/ime/keyboard/org.florisboard.localization/popupMappings/hu.json

I suggest modifications for main alternatives to keys 
o -> ó instead of ö
u -> ú instead of ü
as those (ö and ü) already have their own keys on the keyboard. So ó and ú become more easily reachable.
And this way the main alternatives fit better to the similar letter pairs (e.g. a-á, e-é, i-í) and the layout becomes more conveniently usable.

Update hu.json in popup mappings of Hungarian layout

---

app/build.gradle.kts
app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/about/ThirdPartyLicensesScreen.kt
gradle/libs.versions.toml
gradle/wrapper/gradle-wrapper.properties
lib/android/build.gradle.kts
lib/color/build.gradle.kts
lib/kotlin/build.gradle.kts
lib/native/build.gradle.kts
lib/snygg/build.gradle.kts

This PR upgrades to Compose 1.8.2 and all required other dependencies for binary compatibility.
Also AGP was updated to 8.9.3 and Gradle to 8.11.1.
Also the JVM bytecode target is now 11 for all modules.

Upgrade to Compose 1.8 and Migrate to Compose BOM

---

app/src/main/assets/ime/theme/org.florisboard.themes/stylesheets/floris_day.json
app/src/main/assets/ime/theme/org.florisboard.themes/stylesheets/floris_day_borderless.json
app/src/main/assets/ime/theme/org.florisboard.themes/stylesheets/floris_night.json
app/src/main/assets/ime/theme/org.florisboard.themes/stylesheets/floris_night_borderless.json
app/src/main/assets/ime/theme/org.florisboard.themes/stylesheets/floris_pure_night.json
app/src/main/assets/ime/theme/org.florisboard.themes/stylesheets/floris_pure_night_borderless.json
app/src/main/kotlin/dev/patrickgold/florisboard/ime/clipboard/ClipboardInputLayout.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/smartbar/Smartbar.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/theme/FlorisImeUi.kt
app/src/main/kotlin/dev/patrickgold/florisboard/lib/compose/Resources.kt
app/src/main/res/drawable/ic_content_paste.xml
app/src/main/res/drawable/ic_delete.xml
app/src/main/res/drawable/ic_email.xml
app/src/main/res/drawable/ic_link.xml
app/src/main/res/drawable/ic_phone.xml
app/src/main/res/drawable/ic_pin.xml
app/src/main/res/values/strings.xml
lib/snygg/src/main/kotlin/org/florisboard/lib/snygg/ui/SnyggChip.kt
lib/snygg/src/main/kotlin/org/florisboard/lib/snygg/ui/SnyggRow.kt

- Add ability to filter the clipboard by media types (Closes: #2925)
- Add timestamp display to each clip item within focused popup (Closes: #2926)
- Add `clipboard-filter-row`
- Add `clipboard-filter-chip`
- Add `clipboard-filter-chip-icon`
- Add `clipboard-filter-chip-text`
- Add `clipboard-grid`
- Add `clipboard-item-description`
- Add `clipboard-item-timestamp`
- Add `type` with possible values `text`, `image`, `video`
- Applicable to elements:
- `clipboard-item`
- `clipboard-item-popup`
- `clipboard-item-description`
- `clipboard-filter-chip`
- `clipboard-filter-chip-icon`
- `clipboard-filter-chip-text`
- Add `state` with possible values `active`, `inactive`
- Applicable to elements:
- `clipboard-filter-chip`
- `clipboard-filter-chip-icon`
- `clipboard-filter-chip-text`
- For now …

Clipboard filtering and timestamp display

---

app/src/main/kotlin/dev/patrickgold/florisboard/app/AppPrefs.kt

Closes: What? This hasn't been reported yet!?

Fix always enabling one-hand mode after prefs migration

---

app/src/main/assets/ime/keyboard/org.florisboard.layouts/extension.json
app/src/main/assets/ime/keyboard/org.florisboard.localization/extension.json

Sorry for the second PR on the same topic, but I previously didn't add the Armenian layout properly (I thought I did)(#2871)
It is now appearing this way (no "enter"/"shift" etc)
And here is the fixed version (this PR's changes)
I properly checked, the changes are still minor but correct this time.
Sorry for the inconvenience

Fix Amenian phonetic layout addition

---

app/src/main/kotlin/dev/patrickgold/florisboard/app/AppPrefs.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/theme/ThemeScreen.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/theme/ThemeManager.kt
app/src/main/kotlin/dev/patrickgold/florisboard/lib/util/TimeUtils.kt
gradle/libs.versions.toml
settings.gradle.kts

This PR re-adds time based theme switching which was removed in https://github.com/florisboard/florisboard/commit/96e7f2eeacfd48c6f70901156df127f6e49ec8e5.

Re-add time based theme switching

---

app/build.gradle.kts
app/src/main/kotlin/dev/patrickgold/florisboard/app/FlorisAppActivity.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/Routes.kt
gradle/libs.versions.toml

This PR changes the navigation logic to the type-based navigation introduced in version `2.8.0` of `androidx.navigation:navigation.compose`. The logic of handling deep-links has been adjusted to work with the new type based approach. 
This PR also updates the predictive back animation.

Migrate to type save navigation

---

app/src/main/kotlin/dev/patrickgold/florisboard/FlorisImeService.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/popup/PopupUi.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/smartbar/InlineSuggestionsUi.kt
lib/snygg/src/main/kotlin/org/florisboard/lib/snygg/ui/SnyggSurfaceView.kt

This PR fixes the inline autofill behavior, popups are now correctly drawing over inline autofill chips:
Pros:
- Works with all window background colors
- Works with all **static** window background images
- Works with all **dynamic** window background images (GIFs)
Cons:
- Potentially more error-prone state logic for background
TODO:
Closes #1228

Inline autofill correct draw behavior

---

app/src/main/kotlin/dev/patrickgold/florisboard/app/devtools/DevtoolsOverlay.kt

This PR has disables the message about the failed loading of the stylesheet in BFU mode, as this is expected there.

Disable stylesheet overlay in bfu mode

---

app/src/main/kotlin/dev/patrickgold/florisboard/ime/editor/EditorContent.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/editor/EditorInstance.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboardLayout.kt

This PR fixes multiple small issues with the delete swipe functionality. In particular:
- Add shift+delete swipe behavior if swipe action is set to (delete|select) words precisely
- Fix composite emojis (e.g. X) being broken up (closes #2638)
- Fix forward delete swipe getting stuck if "phantom selected" beyond text end (closes #3017)

Improve delete swipe behavior

---

CONTRIBUTING.md
README.md

This updates the Crowdin domain name to https://crowdin.florisboard.org

Update Crowdin domain name

---

app/src/main/kotlin/dev/patrickgold/florisboard/ime/clipboard/ClipboardInputLayout.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/clipboard/ClipboardManager.kt
app/src/main/res/values/strings.xml

Closes #3074
The delete all button in the clipboard input layout now respects the currently active filters. As with the generic delete all button, pinned items will never be deleted with a bulk action and require manual deletion.

Rework clipboard delete button to respect active filters
