fastlane/metadata/android/en-US/full_description.txt
fastlane/metadata/android/it/full_description.txt
fastlane/metadata/android/it/short_description.txt
fastlane/metadata/android/it/title.txt

check if there are any problems. Maybe the accented letters give problems I don't know

Qw123wh description play store italian

---

app/src/main/assets/ime/config.json
app/src/main/assets/ime/text/characters/extended_popups/fa.json
app/src/main/assets/ime/text/characters/mod/persian.json
app/src/main/assets/ime/text/characters/persian.json
app/src/main/java/dev/patrickgold/florisboard/ime/text/key/KeyCode.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/key/KeyView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/layout/LayoutData.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/layout/LayoutManager.kt
app/src/main/res/values/strings_dont_translate.xml

First of all, thank you for developing this awesome project. This might be the one open-source keyboard that actually works fine. In this pull-request I'm adding the support for Persian layout and this also comes with the ability to have half-space key in any layout that needs one. One important infrastructure change in this pull-request is the ability to load a custom layout modifier for each keyboard layout.

Add support for persian keyboard layout

---

fastlane/metadata/android/en-US/full_description.txt
fastlane/metadata/android/it/full_description.txt

see https://github.com/florisboard/florisboard/issues/1#issuecomment-705187633

formatting full_description.txt

---

app/src/main/assets/ime/config.json
app/src/main/assets/ime/text/characters/extended_popups/hu.json
app/src/main/assets/ime/text/characters/hungarian.json

I added Hungarian layout to this great keyboard.

Add Hungarian layout

---

app/src/main/java/dev/patrickgold/florisboard/ime/media/MediaInputManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/editing/EditingKeyView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/key/KeyView.kt

Fix that the delete key crashes FlorisBoard when holding down on this key. Related to #97.

Fix key delete crash on holding down

---

app/src/main/java/dev/patrickgold/florisboard/ime/core/EditorInstance.kt

I did some basic tests and tried the keyboard in situations discussed in #95 and #64 It works. 
closes #95 closes #64 closes #86

Switch to emulating hardware key press to delete

---

app/src/main/java/dev/patrickgold/florisboard/ime/media/MediaInputManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/popup/KeyPopupManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/editing/EditingKeyView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/key/KeyView.kt
app/src/main/java/dev/patrickgold/florisboard/util/handler_utils.kt
app/src/main/res/drawable/key_popup_bgshape.xml

This PR tries to improve input performance by avoiding unnecessary object allocation. Related to #105
@abh-oss01 @RickyM7 as both of you stated that there's some delay in the input, does the new debug artifact change the input UX, and if so is it now better or worse than before? Thanks in advance!

Improve input UX and performance

---

app/build.gradle
app/src/main/java/dev/patrickgold/florisboard/crashutility/CrashUtility.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/FlorisApplication.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/FlorisBoard.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/InputView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/media/MediaInputManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/media/emoji/EmojiLayoutData.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/TextInputManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/smartbar/SmartbarView.kt

It takes care of Tags and only prints Log statement in debug version.

Switch to Timber for Logging

---

app/src/main/java/dev/patrickgold/florisboard/ime/core/FlorisBoard.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/InputView.kt

InputView Code Cleanup

---

app/src/main/java/dev/patrickgold/florisboard/ime/core/FlorisBoard.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/PrefHelper.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/gestures/SwipeAction.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/key/KeyView.kt
app/src/main/res/values/arrays.xml
app/src/main/res/values/strings.xml
app/src/main/res/xml/prefs_gestures.xml

https://user-images.githubusercontent.com/20506602/103375956-6c5cbe80-4b01-11eb-838c-40d1689dfe3b.mp4
closes #26

Added gesture option to quick switch to previous keyboard

---

app/src/main/assets/ime/theme/floris_day.json
app/src/main/assets/ime/theme/floris_night.json
app/src/main/java/dev/patrickgold/florisboard/ime/core/PrefHelper.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/key/KeyView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/theme/Theme.kt
app/src/main/res/values/strings.xml
app/src/main/res/xml/prefs_theme.xml

https://user-images.githubusercontent.com/20506602/103399315-867cb800-4b66-11eb-835f-f43f14bbaecd.mp4
https://user-images.githubusercontent.com/20506602/103399632-e758c000-4b67-11eb-972c-756dce48b589.mp4
closes #87

Added Option to Hide keys border

---

app/src/main/assets/ime/config.json

Update config for croatian extended popup

Update config.json to include hr keyboard extension

---

app/src/main/assets/ime/text/symbols/mod/default.json
app/src/main/assets/ime/text/symbols/western_default.json

Adds colon character to long press. Fixes #166

---

app/src/main/assets/ime/config.json
app/src/main/assets/ime/text/characters/bulgarian_bds.json
app/src/main/assets/ime/text/characters/bulgarian_phonetic.json
app/src/main/assets/ime/text/characters/extended_popups/bg.json

Hi! This PR should close #235. I hope it's alright.

Add Bulgarian layouts

---

app/src/main/assets/ime/config.json
app/src/main/assets/ime/text/characters/extended_popups/tr.json

Add Turkish extended popups for QWERTY

---

app/src/main/java/dev/patrickgold/florisboard/ime/text/gestures/SwipeGesture.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/key/KeyView.kt

This PR is an attempt to improve the swipe detection mechanism for moving swipe actions (space bar and precise character deletion). I detail, this is what changed:
- The `SwipeGesture` detection utility got an overhaul improvement in the detection of gestures. It should be slightly faster (as it ditches dynamic sized arrays) and the code base has been cleaned up.
- Moving swipes are detected way more precisely and thus will provide a faster feedback to movements.
- Space bar swipe actions now use the new moving detection algorithm, which fixes the inconsistent behavior of the amount of characters selected depending on the speed and CPU load. (Closes #281)
- Space bar swipe left/right can now also be used to move the cursor in the raw input of apps like Termux or SSH clients, as long as …

Improve moving gestures detection and UX

---

app/src/main/assets/ime/theme/floris_black.json
app/src/main/assets/ime/theme/floris_black_borderless.json

Add Floris Black and Floris Black Borderless themes

---

app/src/main/java/dev/patrickgold/florisboard/ime/core/FlorisBoard.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/InputView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/PrefHelper.kt
app/src/main/java/dev/patrickgold/florisboard/ime/onehanded/OneHandedMode.kt
app/src/main/java/dev/patrickgold/florisboard/ime/onehanded/OneHandedPanel.kt
app/src/main/java/dev/patrickgold/florisboard/ime/theme/ThemeManager.kt
app/src/main/java/dev/patrickgold/florisboard/settings/fragments/KeyboardFragment.kt
app/src/main/res/layout/florisboard.xml
app/src/main/res/values/attrs.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml
app/src/main/res/xml/prefs_keyboard.xml

Add ability to set the keyboard width when using one-handed mode. Additionally clean-up of one-handed code.
Closes #96

Add one-handed width option / Improve one-handed code

---

app/src/main/java/dev/patrickgold/florisboard/ime/extension/AssetManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/extension/ExternalContentUtils.kt
app/src/main/java/dev/patrickgold/florisboard/ime/theme/ThemeManager.kt
app/src/main/java/dev/patrickgold/florisboard/settings/ThemeManagerActivity.kt

Fix import theme crash for big files

---

app/src/main/assets/ime/config.json
app/src/main/assets/ime/text/characters/workman.json

This patch adds the Workman keyboard layout. Ref: https://workmanlayout.org

Add the Workman keyboard layout

---

app/src/main/assets/ime/config.json
app/src/main/assets/ime/text/characters/extended_popups/fo.json
app/src/main/assets/ime/text/characters/faroese.json

Hi!
Just added a Faroese layout.
I couldn't test the code, but it's simple, so I can't see why it wouldn't work.
However, I'd be glad if someone could check if it causes an explosion or not.
Also, this is literally my first time contributing anything on Github, so my apologies, if I'm messing something up.
Faroese uses a lot of accents, í, ó, á, í, ý, so that's why they are in "main". Writing is painful without it.

added faroese layout

---

app/src/main/java/dev/patrickgold/florisboard/ime/text/smartbar/CandidateView.kt

Suggestions display mode "Dynamic width & scrollable" should now allow to fill in words consistently. Fixes #533
The clipboard suggestion is now removed after using it. Closes #538

Suggestions UI bug fixing / minor improvements

---

app/src/main/java/dev/patrickgold/florisboard/ime/text/layout/LayoutManager.kt

Fix number row not displaying on characters

---

app/src/main/assets/ime/text/characters/german.json

Qwertz German layout

---

README.md
app/src/main/assets/ime/config.json
app/src/main/assets/ime/text/characters/extended_popups/ckb.json
app/src/main/assets/ime/text/characters/extended_popups/ku.json
app/src/main/assets/ime/text/characters/kurdish.json
app/src/main/assets/ime/text/characters/kurdish_kurmanci.json
app/src/main/assets/ime/text/characters/kurdish_standard.json

Added two new kurdish layouts Kurmanci and Standard kurdish layouts with some correction in codes of current layout.

New kurdish layouts

---

app/src/main/java/dev/patrickgold/florisboard/ime/text/editing/EditingKeyboardView.kt

Fix #571: Set paste key enabled when attached

---

app/src/main/assets/ime/text/characters/extended_popups/fa.json

Improve Persian popups

---

app/src/main/java/dev/patrickgold/florisboard/ime/theme/AdaptiveThemeOverlay.kt

Closes #591
Fix capslock not getting an adaptive color (no issue for this)

Improve adaptive theme for capslock and glide trail

---

app/src/main/java/dev/patrickgold/florisboard/ime/core/InputView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/smartbar/SmartbarView.kt

Display clipboard row in numeric/phone input fields

---

app/src/main/java/dev/patrickgold/florisboard/ime/popup/PopupExtendedView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/popup/PopupLayerView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/popup/PopupView.kt

Fix popup position for rtl mode

---

.github/ISSUE_TEMPLATE/bug_report.md

I'm torn between a big `x` and a small one. Small is less in-your-face, which is nice. Big has the same size as numbers.
Not sure is this is the correct way to create pull requests so please shout at me angrily if something went wrong.

Make version more generic so that it doesn't seem out of date.

---

app/src/main/java/dev/patrickgold/florisboard/ime/text/TextInputManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/key/KeyView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/KeyboardView.kt

Fix space bar up gesture

---

app/src/main/java/dev/patrickgold/florisboard/ime/text/TextInputManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/gestures/SwipeAction.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/key/KeyData.kt
app/src/main/res/values/arrays.xml
app/src/main/res/values/strings.xml

Add Undo, Redo and Cycle keyboard mode gestures

---

app/src/main/assets/ime/text/characters/extended_popups/fr.json

Improve French popups

---

app/src/main/assets/ime/text/characters/extended_popups/sk.json

Update of SK layout

---

app/src/main/java/dev/patrickgold/florisboard/ime/core/FlorisBoard.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/PrefHelper.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/TextInputManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/key/KeyView.kt
app/src/main/res/values/strings.xml
app/src/main/res/xml/prefs_keyboard.xml

Closes #138 
Closes #324 
Closes #610

Improve haptic feedback experience

---

app/src/main/res/values/strings.xml
app/src/main/res/xml/prefs_keyboard.xml

Make clipboard strings translatable

---

app/src/main/java/dev/patrickgold/florisboard/ime/text/TextInputManager.kt

This PR is attempt no. ~1~ 2 at fixing the keyboard flashing. Confirmed to fix #589 after getting feedback on the debug APK.

Possible fix for flashing keyboard

---

app/src/main/java/dev/patrickgold/florisboard/ime/clip/provider/FlorisDatabase.kt

This is a quick patch that stops florisboard from crashing when copying in the AOSP calculator (and derived forks). Also decided to use`coerceToText()` instead of directly using `text` in case it's an intent or something else that isn't an image or text,
Closes #761. Closes #719.

Fix crash when copying from AOSP calculator

---

app/src/main/java/dev/patrickgold/florisboard/settings/ThemeManagerActivity.kt
app/src/main/res/layout/theme_manager_activity.xml

Fix theme manager UI

---

app/src/main/java/dev/patrickgold/florisboard/crashutility/CrashDialogActivity.kt
app/src/main/res/values/strings.xml

Add "Copied to system clipboard" toast to crash dialog

---

app/src/main/java/dev/patrickgold/florisboard/ime/theme/AdaptiveThemeOverlay.kt
app/src/main/java/dev/patrickgold/florisboard/ime/theme/ThemeManager.kt

Fix adaptive theme memory management

---

app/src/main/java/dev/patrickgold/florisboard/ime/keyboard/KeyboardView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboardView.kt

Fix for Double NaN crashes

---

app/src/main/java/dev/patrickgold/florisboard/ime/core/FlorisBoard.kt
app/src/main/java/dev/patrickgold/florisboard/ime/media/MediaInputManager.kt

Fix AppCompat theme crash for Huawei devices

---

app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboardView.kt

Closes #825 
Possibly related: #756, #716

Fix dynamic text size infinite loop bug

---

app/src/main/java/dev/patrickgold/florisboard/ime/text/gestures/GlideTypingClassifier.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/gestures/GlideTypingGesture.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/gestures/GlideTypingManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/gestures/StatisticalGlideTypingClassifier.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboardView.kt

Closes #802 
@X-yl if possible could you have a look what I am missing? I tried around a lot, but in the end the glide trail is drawn, but no words are generated and I don't really know where in the glide typing implementation the error is. Thanks in advance!

Re-implement glide typing for new keyboard view

---

app/src/main/java/dev/patrickgold/florisboard/ime/clip/ClipboardInputManager.kt

No idea why it was on a different thread before? Think I just copied it like that from MediaInputManager. Oops.
--- 
Closes #840

Set up clipboard history view on main thread

---

app/src/main/java/dev/patrickgold/florisboard/ime/text/gestures/StatisticalGlideTypingClassifier.kt

Closes #847
After fixing this bug the stable branch needs a hotfix release (v0.3.12). Thus the next "big" release is v0.3.13.

Fix glide logic not triggering when shift/caps is active

---

app/src/main/cpp/dev_patrickgold_florisboard_ime_nlp_SuggestionList.cpp
app/src/main/cpp/ime/nlp/CMakeLists.txt
app/src/main/cpp/ime/nlp/nlp.h
app/src/main/cpp/ime/nlp/suggestion_list.cpp
app/src/main/cpp/ime/nlp/suggestion_list.h
app/src/main/cpp/ime/nlp/token.cpp
app/src/main/cpp/ime/nlp/token.h

This PR improves the C++ code base introduced in #858 by using smart pointers instead of raw C pointers.

Improve C++ code base

---

app/src/main/assets/ime/text/characters/hebrew.json

fixed bottom half layout its was reversed and incorrect.
Closes #897

Fix hebrew characters

---

app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboardView.kt
app/src/main/res/values/dimens.xml

Fix space bar gestures for non-repeating actions

---

app/src/main/java/dev/patrickgold/florisboard/crashutility/CrashUtility.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/FlorisBoard.kt

Fix crash loops from occurring after a crash

---

app/src/main/java/dev/patrickgold/florisboard/settings/AboutActivity.kt
app/src/main/res/drawable/ripple_click.xml
app/src/main/res/layout/about_activity.xml
app/src/main/res/values/strings.xml

Copy version string to clipboard on click on the version

---

app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboardView.kt

Fix keys not showing a shadow

---

app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboardView.kt
app/src/main/res/values/dimens.xml

Fix space bar text too large

---

app/src/main/assets/ime/text/numeric/row/devanagari.json

Fixed Devanagari Codes

---

app/src/main/java/dev/patrickgold/florisboard/ime/core/EditorInstance.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/FlorisBoard.kt
app/src/main/java/dev/patrickgold/florisboard/ime/keyboard/KeyboardState.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/TextInputManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboardView.kt

Fix crash when using delete left swipe in raw editors

---

app/src/main/java/dev/patrickgold/florisboard/ime/media/emoticon/EmoticonKeyData.kt
app/src/main/java/dev/patrickgold/florisboard/ime/media/emoticon/EmoticonKeyboardView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/media/emoticon/EmoticonLayoutData.kt

Fix emoticon layout missing

---

app/src/main/java/dev/patrickgold/florisboard/FlorisApplication.kt
app/src/main/java/dev/patrickgold/florisboard/ime/clip/ClipboardHistoryView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/clip/ClipboardInputManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/FlorisBoard.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/InputView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/InputWindowView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/keyboard/KeyboardState.kt
app/src/main/java/dev/patrickgold/florisboard/ime/media/MediaInputManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/media/MediaInputView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/TextInputManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/editing/EditingKeyboardView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboardView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/smartbar/CandidateView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/smartbar/SmartbarView.kt
app/src/main/java/dev/patrickgold/florisboard/settings/ThemeManagerActivity.kt
app/src/main/res/layout/florisboard.xml
app/src/main/res/layout/smartbar.xml
app/src/main/res/layout/text_input_layout.xml

Moderate overhaul for the keyboard UI initialization and Smartbar state.
Closes #969
Closes #987

Fix keyboard state bug for the active mode

---

app/src/main/java/dev/patrickgold/florisboard/ime/core/EditorInstance.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/FlorisBoard.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/InputEventDispatcher.kt
app/src/main/java/dev/patrickgold/florisboard/ime/keyboard/KeyboardState.kt
app/src/main/java/dev/patrickgold/florisboard/ime/keyboard/KeyboardView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/popup/PopupLayerView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/popup/PopupManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/TextInputManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/gestures/StatisticalGlideTypingClassifier.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboard.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboardView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/smartbar/SmartbarView.kt
app/src/main/java/dev/patrickgold/florisboard/settings/ThemeEditorActivity.kt
app/src/main/java/dev/patrickgold/florisboard/settings/ThemeManagerActivity.kt
app/src/main/res/layout/text_input_layout.xml

This PR is yet another attempt at fixing and improving the rendering of the keyboard. This PR finally gets the native elevation up and running, making the shadows look really cool again.
Additionally:
Closes #988 (Hopefully)
Closes #939

Rework TextKeyboard rendering

---

app/src/main/assets/ime/text/characters/halmak.json

Adding Halmak, an AI designed keyboard layout.
https://github.com/MadRabbit/halmak

Add the Halmak keyboard layout

---

app/src/main/java/dev/patrickgold/florisboard/ime/clip/FlorisClipboardManager.kt

Move new clipboard items with the same content to the beginning

---

app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboardView.kt

Fix cut off hints in borderless themes

---

app/src/main/assets/ime/text/characters/dghp.json
app/src/main/assets/ime/text/characters/nalmy.json
app/src/main/assets/ime/text/characters/sangaline.json

Layouts were found [here](http://sangaline.com/post/finding-an-optimal-keyboard-layout-for-swype/) and [here](https://jasmcole.com/2017/06/04/swype-right/), added as mentioned in #76

Add keyboard layouts optimized for swype input

---

app/src/main/AndroidManifest.xml
app/src/main/java/dev/patrickgold/florisboard/FlorisApplication.kt
app/src/main/java/dev/patrickgold/florisboard/ime/clip/FlorisClipboardManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/Preferences.kt

[Direct boot](https://developer.android.com/training/articles/direct-boot) allow an app to work before [Credential protected storage is available](https://www.youtube.com/watch?v=fb2Zwmc3Sp4), I have not done anything excellent because that's useless IMHO, UI works in default mode and override it with user configuration as soon credential protected storage is available.
Project might consider using device protected storage instead of credential protected storage for configuration and other non sensitive stuff but that's up to you. I am no one to make that decision.
This is BASIC implementation more testing and development might be needed.
I have tested it on Poco f1 and Pixel 4 running on android 11.
Closes #485 
Closes #1019 
Closes #1046

added support for direct boot

---

app/src/main/assets/ime/config.json
app/src/main/assets/ime/text/characters/extended_popups/lt.json

Add support for Lithuanian layout / popup mapping

---

app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboard.kt

Possible fix for NaN crash

---

app/src/main/assets/ime/text/numeric/advanced/western_arabic_pc.json
app/src/main/assets/ime/text/numeric/western_arabic_pc.json

Add alternative numpad with PC arrangement of digits

---

app/src/main/java/dev/patrickgold/florisboard/settings/ThemeEditorActivity.kt

Fix theme editor preview looking distorted

---

app/src/main/java/dev/patrickgold/florisboard/ime/core/InputEventDispatcher.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboardView.kt

This PR is a possible fix for the repeating delete/arrow key bug a lot of people reported. Thorough testing needs to be done though before we can say for sure it is fixed.
Closes #986

Possibly fix repeating delete key

---

app/src/main/java/dev/patrickgold/florisboard/ime/keyboard/InputFeedbackManager.kt
app/src/main/java/dev/patrickgold/florisboard/settings/fragments/InputFeedbackFragment.kt
app/src/main/java/dev/patrickgold/florisboard/settings/fragments/KeyboardFragment.kt
app/src/main/res/values/strings.xml

Improvements for Rework audio and haptic feedback

---

app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/TextKey.kt

Fix popup merge bug for group assigned keys

---

app/src/main/java/dev/patrickgold/florisboard/ime/core/EditorInstance.kt

Fix Smartbar Cut/Copy buttons limited to few characters

---

app/build.gradle.kts
app/src/main/AndroidManifest.xml
app/src/main/java/dev/patrickgold/florisboard/FlorisSpellCheckerService.kt
app/src/main/java/dev/patrickgold/florisboard/ime/spelling/SpellingService.kt

Spell checker Part 4: Bug fixing & improvements

---

app/src/main/assets/ime/text/characters/extended_popups/ja-JP-jis.json
app/src/main/assets/ime/text/symbols2/cjk.json

fix: Add katakana middle dot to JIS popups

---

app/src/main/assets/ime/text/symbols/western-additional-symbols.json

Extremely sorry :(
I messed up the symbols-additional layout

fix '>' symbol

---

app/src/main/java/dev/patrickgold/florisboard/app/ui/settings/localization/SubtypeEditorScreen.kt

Fix subtype show all button causing crash

---

app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/characters/ipa.json

Fix some character codes in ipa layout

---

app/src/main/java/dev/patrickgold/florisboard/app/prefs/AppPrefs.kt
app/src/main/java/dev/patrickgold/florisboard/app/ui/settings/clipboard/ClipboardScreen.kt
app/src/main/java/dev/patrickgold/florisboard/ime/clipboard/ClipboardInputLayout.kt
app/src/main/java/dev/patrickgold/florisboard/ime/clipboard/ClipboardManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/clipboard/provider/ClipboardDatabase.kt
app/src/main/java/dev/patrickgold/florisboard/ime/keyboard/KeyboardManager.kt
app/src/main/res/values/strings.xml

See #1235 
Closes #1447 
Closes #1448 
Closes #1449

Preference Rework Part 8.5: Small improvements

---

app/src/main/java/dev/patrickgold/florisboard/app/ui/Routes.kt
app/src/main/java/dev/patrickgold/florisboard/app/ui/settings/dictionary/DictionaryScreen.kt
app/src/main/java/dev/patrickgold/florisboard/app/ui/settings/dictionary/UserDictionaryScreen.kt
app/src/main/java/dev/patrickgold/florisboard/common/Validation.kt
app/src/main/java/dev/patrickgold/florisboard/ime/dictionary/UserDictionary.kt
app/src/main/res/values/strings.xml

See #1235 
Closes #1066 
Closes #1544

Re-implement user-dictionary settings UI

---

app/build.gradle.kts
app/src/main/java/dev/patrickgold/florisboard/app/prefs/AppPrefs.kt
app/src/main/java/dev/patrickgold/florisboard/app/ui/Routes.kt
app/src/main/java/dev/patrickgold/florisboard/app/ui/settings/HomeScreen.kt
app/src/main/java/dev/patrickgold/florisboard/app/ui/settings/media/MediaScreen.kt
app/src/main/java/dev/patrickgold/florisboard/ime/media/emoji/Emoji.kt
app/src/main/java/dev/patrickgold/florisboard/ime/media/emoji/EmojiPaletteView.kt
app/src/main/java/dev/patrickgold/florisboard/ime/media/emoji/EmojiRecentlyUsedHelper.kt
app/src/main/java/dev/patrickgold/florisboard/ime/media/emoji/EmojiSet.kt
app/src/main/res/values/strings.xml
build.gradle.kts

Closes #132 
Closes #1607 
Closes #1610

Improve emoji implementation

---

app/src/main/assets/ime/keyboard/org.florisboard.localization/popupMappings/ku.json

Fix kurmanji kurdish letter ş when user press this letter it was writes wrong letter û

Fix kurmanji kurdish letter ş

---

app/src/main/java/dev/patrickgold/florisboard/ime/clipboard/ClipboardInputLayout.kt
app/src/main/java/dev/patrickgold/florisboard/ime/clipboard/ClipboardManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/EditorInstance.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/gestures/StatisticalGlideTypingClassifier.kt

Fix #801 
Fix #887 
Fix #927 
Fix #1398 
Fix #1632 
Fix #1140 
Fix #1301 
Fix #1512 
Fix #1519 
Fix #1662 
Fix #1660

Fix clipboard and input logic crashes

---

app/src/main/java/dev/patrickgold/florisboard/common/Unicode.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyData.kt

This PR fixes #1679, where a lot of Arabic combing characters where not displayed correctly.

Fix Arabic combining characters not displaying correctly

---

app/src/main/assets/ime/keyboard/org.florisboard.localization/popupMappings/fa.json

Fix main popup for "ﺍ"

---

app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/characters/hebrew.json

Opening this initially as a draft, to gather feedback while I research how to deal better with the combining characters, which don’t show nicely in the diff and in the source code.

Add Hebrew niqqud and some punctuation marks

---

app/src/main/java/dev/patrickgold/florisboard/common/FlorisLocale.kt

Fix language names not titlecase for some locales

---

app/src/main/assets/ime/theme/org.florisboard.themes/stylesheets/floris_day.json
app/src/main/assets/ime/theme/org.florisboard.themes/stylesheets/floris_night.json
app/src/main/java/dev/patrickgold/florisboard/FlorisImeService.kt
app/src/main/java/dev/patrickgold/florisboard/app/res/Resources.kt
app/src/main/java/dev/patrickgold/florisboard/app/ui/components/FlorisButtons.kt
app/src/main/java/dev/patrickgold/florisboard/common/android/AndroidInternalR.kt
app/src/main/java/dev/patrickgold/florisboard/ime/core/EditorInstance.kt
app/src/main/java/dev/patrickgold/florisboard/ime/lifecycle/LifecycleInputMethodService.kt
app/src/main/java/dev/patrickgold/florisboard/ime/theme/FlorisImeUi.kt
app/src/main/java/dev/patrickgold/florisboard/ime/theme/FlorisImeUiSpec.kt
app/src/main/java/dev/patrickgold/florisboard/util/DebugSummarizeUtils.kt
app/src/main/res/drawable/edit_text_background.xml

This PR (re-)adds support for extracted landscape input:
Closes #1711

Add support for ExtractedLandscapeInput

---

app/src/main/java/dev/patrickgold/florisboard/ime/keyboard/KeyboardManager.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboardLayout.kt

Fix glide typing state and drawing bugs

---

app/src/main/java/dev/patrickgold/florisboard/ime/text/composing/HangulUnicode.kt

Korean composition of medial+final and final+final

---

app/src/main/java/dev/patrickgold/florisboard/FlorisImeService.kt
app/src/main/java/dev/patrickgold/florisboard/app/ui/devtools/DevtoolsOverlay.kt

Possibly closes #1758
Closes #1760

Fix extracted input UI issues

---

app/src/main/assets/ime/keyboard/org.florisboard.layouts/extension.json
app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/characters/german2.json
app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/charactersMod/persian2.json
app/src/main/assets/ime/keyboard/org.florisboard.localization/popupMappings/fa2.json

fixed the said issues and reordered the emoji icon in persian2 layout based in swiftkey keyboard.
Closes #1737 
Closes #1746

fixing #1737 & #1746 & Persian2 layout

---

app/src/main/java/dev/patrickgold/florisboard/app/ui/components/DisposableLifecycleEffect.kt
app/src/main/java/dev/patrickgold/florisboard/ime/lifecycle/LifecycleInputMethodService.kt
app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboardLayout.kt

Fix key visuals and popups getting stuck

---

app/src/main/kotlin/dev/patrickgold/florisboard/app/AppPrefs.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/devtools/DevtoolsScreen.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/theme/EditRuleDialog.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/core/EditorInstance.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/keyboard/Keyboard.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/keyboard/KeyboardManager.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/gestures/SwipeAction.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/gestures/SwipeGesture.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/key/KeyCode.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyData.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboard.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboardLayout.kt
app/src/main/res/values/strings.xml

This PR attempts to fix commonly reported bugs in the glide, input and gesture logic.
Closes #1715 
Closes #1777 
Closes #1794

Fix issues with gesture detection and glide/input logic

---

app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/characters/kurdish_standard.json
app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/charactersMod/kurdish.json
app/src/main/assets/ime/keyboard/org.florisboard.localization/popupMappings/ckb.json

Makes some changes in Kurdish layouts also added some symbols that usually using in Kurdish language.

Update Kurdish layout and overall improvements 

---

app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/theme/SnyggValueIcon.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/theme/ThemeTranslations.kt
app/src/main/res/values/strings.xml

This PR addresses minor issues with the overall theme engine and the theme prefs/editor
Closes #1838

Fix minor theme issues (kbd + prefs)

---

app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/advanced/BackupScreen.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/editor/AbstractEditorInstance.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboardLayout.kt

Fix minor keyboard logic and Settings issues

---

app/src/main/assets/ime/keyboard/org.florisboard.layouts/extension.json
app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/characters/dvorak_es.json

Not that I speak Spanish, it was just easy to add. Please let me know if I should label it differently. Gboard for example names it "Dvorak (ÑÇ)".
Closes #1853

Add DvorakES layout

---

app/src/main/kotlin/dev/patrickgold/florisboard/ime/clipboard/ClipboardInputLayout.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/nlp/NlpManager.kt
app/src/main/kotlin/dev/patrickgold/florisboard/lib/util/NetworkUtils.kt
app/src/main/res/values/strings.xml

Add clipboard URL and Email detection

---

app/src/main/kotlin/dev/patrickgold/florisboard/FlorisImeService.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/editor/AbstractEditorInstance.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/editor/EditorInstance.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/editor/InputAttributes.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/input/InputFeedbackController.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/keyboard/ComputingEvaluator.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/keyboard/KeyboardManager.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/keyboard/KeyboardState.kt

This PR tries to address a few performance issues and to reduce high CPU usage in critical events such as touch events and key down/up/repeat.

Improve input feedback controller performance

---

app/src/main/kotlin/dev/patrickgold/florisboard/ime/editor/AbstractEditorInstance.kt

Fix auto-spacing incorrectly triggered for non-Appender composers

---

app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyData.kt

This PR addresses a minor issue in the AutoTextKey behavior, which ignored the subtype locale, thus creating issues for specific locales and characters such as Turkish.
Closes #1840

Adjust AutoTextKey behavior to respect subtype locale (e.g. for Turkish)

---

app/src/main/kotlin/dev/patrickgold/florisboard/ime/editor/EditorInstance.kt

Fix phantom spacing not working correctly for 1 letter words

---

app/src/main/kotlin/dev/patrickgold/florisboard/ime/clipboard/ClipboardInputLayout.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/nlp/NlpManager.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/nlp/SuggestionCandidate.kt
app/src/main/kotlin/dev/patrickgold/florisboard/lib/util/NetworkUtils.kt
app/src/main/res/drawable/ic_phone.xml
app/src/main/res/values/strings.xml

This PR addresses several issues and feature proposals regarding NetworkUtils regex issues (crashes) and also adds phone number detection for copied clipboard items (same as for emails and URLs now).
Addresses #1889 
Addresses and Closes #1971 
Closes #1970

Clipboard and NetworkUtils regex fixes

---

app/src/main/assets/ime/keyboard/org.florisboard.localization/popupMappings/pl.json

Fix accent ordering of z in Polish popup mapping

---

app/src/main/kotlin/dev/patrickgold/florisboard/FlorisImeService.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/clipboard/ClipboardInputLayout.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/keyboard/KeyboardManager.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/keyboard/KeyboardState.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/nlp/NlpManager.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/sheet/BottomSheetHostUi.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/smartbar/Smartbar.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/smartbar/quickaction/QuickActionsOverflowPanel.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/smartbar/quickaction/QuickActionsRow.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/TextInputLayout.kt

This PR aims to address the most important crashes and bugs introduced with #2012 and the latest release v0.4.0-alpha03.
Closes #1760 
Closes #2025 
Closes #2026 
Closes #2029 
Closes #2033 
Closes #2035

Smartbar rework hotfixes

---

app/src/main/assets/ime/keyboard/org.florisboard.currencysets/extension.json
app/src/main/assets/ime/keyboard/org.florisboard.layouts/extension.json
app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/characters/bengali_bd.json
app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/numericAdvanced/bengali.json
app/src/main/assets/ime/keyboard/org.florisboard.localization/extension.json
app/src/main/assets/ime/keyboard/org.florisboard.localization/popupMappings/bn-BD.json

This PR contains the Bengali keyboard layout, followed by the contribution guideline provided [here](https://github.com/florisboard/florisboard/blob/master/CONTRIBUTING.md). I hope everything is okay to merge this request.
<table>
<tr>
<td><img src="https://user-images.githubusercontent.com/77199897/191672061-d276bf37-c125-4abb-a553-908134fd9217.png"></td>
<td><img src="https://user-images.githubusercontent.com/77199897/191672085-97357ecc-6792-41d8-a0de-cc5b6559a42e.png"></td>
</tr>
<tr>
<td><img src="https://user-images.githubusercontent.com/77199897/191672556-d3c1cb92-7dea-4c93-b909-d4282c374a63.png"></td>
<td><img src="https://user-images.githubusercontent.com/77199897/191672109-684aa07a-bc90-4c35-ad8a-8f402ca7b86c.png"></td>
</tr>
</table>

Bengali keyboard layout

---

app/src/main/assets/ime/keyboard/org.florisboard.localization/extension.json
app/src/main/assets/ime/keyboard/org.florisboard.localization/popupMappings/ast.json
crowdin.yml

This PR is the continuation of what I f****d up in https://github.com/florisboard/florisboard/pull/2062

Add support for Asturian layout

---

app/src/main/assets/ime/keyboard/org.florisboard.localization/extension.json
app/src/main/assets/ime/keyboard/org.florisboard.localization/popupMappings/kab.json

Added support for Kabyle (Latin script) with the default qwerty layout

Add New Kabyle (Taqbaylit) Popup Mapping

---

app/src/main/assets/ime/keyboard/org.florisboard.layouts/extension.json
app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/characters/tamil.json
app/src/main/assets/ime/keyboard/org.florisboard.localization/extension.json

This is my first pull request of my life :) 
I hope everything is fine and it will help the project
Thanks for your review

Add Tamil layout (#261) & (#368)

---

app/src/main/assets/ime/keyboard/org.florisboard.layouts/extension.json
app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/characters/slovenian.json
app/src/main/assets/ime/keyboard/org.florisboard.localization/extension.json
app/src/main/assets/ime/keyboard/org.florisboard.localization/popupMappings/sl-SI.json

Hi there,
I added Slovenian layout to the keyboard, based on qwertz layout.
Closes #1469

Add slovenian layout

---

app/src/main/res/values-pl/strings.xml
fastlane/metadata/android/pl-PL/full_description.txt
fastlane/metadata/android/pl-PL/short_description.txt

Update strings.xml PL

---

.github/workflows/android.yml
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md
ROADMAP.md

This PR is a preparation for the public announcement later today/tomorrow regarding the project restructuring & getting the project back on track.

Add new ROADMAP, CODE OF CONDUCT and rewrite CONTRIBUTING

---

app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/numericRow/thai.json

It's my first time ever creating a pull request. However, the needed change should be trivial to do, and I think I've correctly done it.
Fixes #2319

Fix wrong character in Thai number row layout

---

app/build.gradle.kts
app/src/main/kotlin/dev/patrickgold/florisboard/FlorisApplication.kt
gradle/libs.versions.toml

This should significantly reduce build times and fix some compilation issues

Include new NLP submodule build system

---

app/build.gradle.kts
app/src/main/assets/ime/keyboard/org.florisboard.layouts/extension.json
app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/characters/dvorak_de.json
app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/charactersMod/dvorak_de.json

Add german variant of the dvorak layout

---

app/src/main/kotlin/dev/patrickgold/florisboard/app/setup/SetupScreen.kt
app/src/main/kotlin/dev/patrickgold/florisboard/lib/android/AndroidVersion.kt
app/src/main/kotlin/dev/patrickgold/florisboard/lib/util/InputMethodUtils.kt

Closes #2344
Additionally auto-return from system UI when enabling should be fixed too.

Fix IME enabled/selected checker failing on API 34+

---

app/src/main/kotlin/dev/patrickgold/florisboard/ime/clipboard/ClipboardManager.kt

fix pinned items getting unpinned when copying the same content again

---

app/src/main/kotlin/dev/patrickgold/florisboard/ime/keyboard/KeyboardManager.kt

fix primary clipboard entry accessible while phone is locked

---

app/src/main/kotlin/dev/patrickgold/florisboard/app/AppPrefs.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/keyboard/KeyboardScreen.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/input/CapitalizationBehavior.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/keyboard/KeyboardManager.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/keyboard/SpaceBarMode.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboardLayout.kt
app/src/main/res/values/strings.xml

Added option to select between:
(Spacebar character),
(Nothing) and
(Current language)
Closes: #2350 
Closes: #419

Implement option to cycle throu the capitalization modes and add option to set spacebar to the spacebar character

---

app/src/main/kotlin/dev/patrickgold/florisboard/ime/nlp/NlpManager.kt

- This PR addresses an issue where empty or invalid clipboard items that could lead to incorrect suggestions.
- It introduces validation logic to ensure only meaningful content is suggested.
- The issue was observed when apps like KDE Connect added empty or special character-only items to the clipboard.
- The `ClipboardSuggestionProvider` previously lacked validation for such cases.
- Added validation for empty clipboard items.
- Enhanced validation to handle special characters (newlines, tabs).
- Introduced private methods and constants for improved readability and maintainability.
Fixes #2386

Refine Clipboard Suggestion Validation to Prevent Empty and Invalid Items

---

app/src/main/assets/ime/keyboard/org.florisboard.layouts/extension.json
app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/characters/udmurt_compact.json
app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/characters/udmurt_extended.json
app/src/main/assets/ime/keyboard/org.florisboard.localization/extension.json
app/src/main/assets/ime/keyboard/org.florisboard.localization/popupMappings/udm.json

Hi,
I added 2 Udmurt layouts (extended and compact) to the keyboard, based on russian layouts.

Add Udmurt layouts.

---

app/src/main/kotlin/dev/patrickgold/florisboard/ime/clipboard/provider/ClipboardDatabase.kt

Fix huge clipboard text items causing clipboard history crash

---

app/src/main/kotlin/dev/patrickgold/florisboard/ime/core/Subtype.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/media/MediaInputLayout.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/media/emoji/EmojiData.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/media/emoji/EmojiLayoutData.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/media/emoji/EmojiPaletteView.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/media/emoji/EmojiSuggestionProvider.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/nlp/NlpManager.kt

This PR should fix #2460.
@snaik20 I am requesting your review as you were the original implementer and need to know if I messed up something (like for instance the supported emoji set where I am not sure how to use that with the new logic)

Fix emoji suggestion logic

---

app/src/main/kotlin/dev/patrickgold/florisboard/FlorisImeService.kt

Fix fullscreen input mode in portrait orientation

---

app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/characters/bengali_bd.json
app/src/main/assets/ime/keyboard/org.florisboard.localization/popupMappings/bn-BD.json

This PR aims to incorporate the latest Unijoy layout into the bn-BD layout and tune the popup keys.

Updated bn-BD layout

---

app/build.gradle.kts
app/src/main/kotlin/dev/patrickgold/florisboard/FlorisImeService.kt
app/src/main/kotlin/dev/patrickgold/florisboard/lib/compose/SystemUi.kt
gradle/libs.versions.toml

1. Remove accompanist.systemuicontroller dependency
2. Replace old api with window/view apis
> [!IMPORTANT]
> This pull request must be tested by people who have had the problem before it is merged. 
Closes #2461

Remove accompanist.systemuicontroller and migrate to window/view apis 

---

app/src/main/kotlin/dev/patrickgold/florisboard/app/ext/ExtensionEditScreen.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/localization/SubtypeEditorScreen.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/clipboard/ClipboardInputLayout.kt
app/src/main/kotlin/dev/patrickgold/florisboard/lib/compose/FlorisChip.kt
app/src/main/kotlin/dev/patrickgold/florisboard/lib/compose/PreviewKeyboardField.kt

fix suggestion engine selection crash

---

app/src/main/kotlin/dev/patrickgold/florisboard/FlorisCopyToClipboardActivity.kt

This PR removes the use of the deprecated Swipeable API.

remove deprecated Swipeable API and switch to M3 ModalBottomSheet

---

app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/HowDidWeGetHere.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/TextInputLayout.kt

Related to #2362
This PR tries to add a detection for the "All keys invisible" bug and show a warning box.

Add possible detection for "All keys invisible" bug

---

app/src/main/assets/ime/keyboard/org.florisboard.layouts/extension.json
app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/characters/jcuken_interslavic.json

Add ЈЦУКЕН interslavic keyboard layout

---

app/src/main/assets/ime/keyboard/org.florisboard.layouts/extension.json
app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/characters/colemak_dhm.json

Piggybacking off of #714, this adds the mod-DH variant of colemak using the flex format. Let me know if you have any concerns!

Add support for the layout Colemak-DHm

---

app/src/main/AndroidManifest.xml
app/src/main/kotlin/dev/patrickgold/florisboard/app/FlorisAppActivity.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/Routes.kt

Add the following scheme: `ui://florisboard/<route>` to allow linking into the FlorisBoard UI

Add deep link support for UI

---

app/src/main/kotlin/dev/patrickgold/florisboard/app/Routes.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/ext/CheckUpdatesScreen.kt
app/src/main/res/values/strings.xml

This PR adds the CheckUpdatesScreen. This screen is opened from within the addons store ui.

Add CheckUpdatesScreen

---

app/src/main/kotlin/dev/patrickgold/florisboard/app/ext/ExtensionHomeScreen.kt

This PR removes the wrong preference category in the Addons & Extensions screen.

Remove preference category from ExtensionHomeScreen

---

README.md

This PR updates the README.md to the current project status. 
The dependency list has been updated and the addons store is now mentioned in the readme.

Update README.md to the current status

---

app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/keyboard/KeyboardScreen.kt

Disable hinted number row toggle if number row is enabled

---

app/src/main/AndroidManifest.xml
app/src/main/kotlin/dev/patrickgold/florisboard/ime/clipboard/FlorisCopyToClipboardActivity.kt

This PR moves the FlorisCopyToClipboardActivity from `dev/patrickgold/florisboard/FlorisCopyToClipboardActivity.kt`  to `dev/patrickgold/florisboard/ime/clipboard/FlorisCopyToClipboardActivity.kt`

Move FlorisCopyToClipboardActivity to `ime.clipboard`

---

app/src/main/kotlin/dev/patrickgold/florisboard/app/FlorisAppActivity.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/sheet/BottomSheetHostUi.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/smartbar/CandidatesRow.kt
app/src/main/kotlin/dev/patrickgold/florisboard/lib/compose/Modifier.kt

This PR fixes the problem that the content of the settings app was covered by the display cutout in landscape mode

Fix incorrect drawing behavior with display cutouts

---

app/src/main/kotlin/dev/patrickgold/florisboard/ime/nlp/latin/LatinLanguageProvider.kt

This PR removes the placeholder suggestions. (next0, next1, next2, next3, etc...)

Remove placeholder suggestions

---

app/build.gradle.kts
app/src/main/kotlin/dev/patrickgold/florisboard/lib/ext/ExtensionValidation.kt
build.gradle.kts
gradle/libs.versions.toml
lib/kotlin/build.gradle.kts
lib/snygg/build.gradle.kts
settings.gradle.kts

Upgrade to Kotlin 2.0

---

app/src/main/assets/ime/keyboard/org.florisboard.layouts/extension.json

Tamil was not in the dropdown for layout. Added now and checked using debug app. All working fine. Please merge to main
Closes: #2558

Added Tamil to layout

---

app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboardLayout.kt

This PR fixes issues regarding size state update bugs introduced by JC 1.7

Fix keyboard key size not properly updating

---

app/schemas/dev.patrickgold.florisboard.ime.clipboard.provider.ClipboardHistoryDatabase/3.json
app/src/main/kotlin/dev/patrickgold/florisboard/ime/clipboard/ClipboardInputLayout.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/clipboard/provider/ClipboardDatabase.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/media/MediaInputLayout.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/nlp/NlpManager.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/nlp/SuggestionCandidate.kt
app/src/main/res/values/strings_dont_translate.xml

Clipboard History enhancements

---

app/src/main/kotlin/dev/patrickgold/florisboard/ime/nlp/NlpManager.kt

This PR removes the unnecessary clipboard suggestions with sensitive clip data.

Add fix for sensitive clipboard suggestions

---

app/src/main/kotlin/dev/patrickgold/florisboard/ime/popup/PopupUiController.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboardLayout.kt

This PR fixes state issues in TextKeyboardLayout and also removes unused smartbar keyboard support.
Closes #2629 
Closes #2642
Closes #2648

Fix state issues in TextKeyboardLayout (popups)

---

app/src/main/kotlin/dev/patrickgold/florisboard/ime/theme/ThemeManager.kt

This PR fixes the single icon style for inline autofill suggestions from password managers.

Fix inline autofill single icon style (#2628)

---

app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/media/MediaScreen.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/media/emoji/EmojiHistory.kt
app/src/main/res/values/strings.xml

Add option to delete EmojiHistory from settings screen

---

app/src/main/kotlin/dev/patrickgold/florisboard/lib/util/AppVersionUtils.kt
gradle.properties
gradle/libs.versions.toml
gradle/wrapper/gradle-wrapper.properties
lib/android/src/main/kotlin/org/florisboard/lib/android/AndroidVersion.kt

This PR upgrades to target SDK 35 (Android 15).
Identified issues:
- Bottom bar space not existent. Might be fixed by #2722

Upgrade to Android 15

---

app/src/main/kotlin/dev/patrickgold/florisboard/FlorisImeService.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/AppPrefs.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/devtools/DevtoolsOverlay.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/devtools/DevtoolsScreen.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/keyboard/KeyboardManager.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/keyboard/LayoutManager.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/HowDidWeGetHere.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/TextInputLayout.kt
app/src/main/kotlin/dev/patrickgold/florisboard/lib/ext/ExtensionManager.kt
app/src/main/res/values/strings.xml

This PR adds better detection for the "All keys invisible" bug, reported in https://github.com/florisboard/florisboard/issues/2362.

Add better detection for all keys visible bug

---

app/src/main/kotlin/dev/patrickgold/florisboard/ime/editor/AbstractEditorInstance.kt
lib/snygg/src/main/kotlin/org/florisboard/lib/snygg/ui/SnyggModifiers.kt
lib/snygg/src/main/kotlin/org/florisboard/lib/snygg/value/SnyggMaterialYouValue.kt

https://developer.android.com/about/versions/15/behavior-changes-15#openjdk-api-changes

Fix NoSuchMethodError: removeFirst() on android 14 and lower

---

app/src/main/kotlin/dev/patrickgold/florisboard/app/AppPrefs.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/devtools/DevtoolsOverlay.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/devtools/DevtoolsScreen.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/keyboard/LayoutManager.kt

Fixes some issues introduced with https://github.com/florisboard/florisboard/pull/2735

Fix issues with all keys invisible detection

---

app/src/main/kotlin/dev/patrickgold/florisboard/app/devtools/DevtoolsScreen.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/keyboard/KeyboardManager.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/nlp/BreakIteratorGroup.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboardCache.kt
app/src/main/kotlin/dev/patrickgold/florisboard/lib/ext/ExtensionManager.kt
app/src/main/kotlin/dev/patrickgold/florisboard/lib/util/DebugSummarizeUtils.kt
app/src/main/kotlin/dev/patrickgold/florisboard/lib/util/LaunchUtils.kt
settings.gradle.kts

This PR tries to finally resolve the all keys invisible bug from #2362

Possible fixes for all keys invisible bug

---

app/src/main/assets/ime/keyboard/org.florisboard.layouts/extension.json
app/src/main/assets/ime/keyboard/org.florisboard.layouts/layouts/characters/hindi_in.json
app/src/main/assets/ime/keyboard/org.florisboard.localization/extension.json
app/src/main/assets/ime/keyboard/org.florisboard.localization/popupMappings/hi-IN.json
app/src/main/kotlin/dev/patrickgold/florisboard/lib/FlorisLocale.kt

All characters of Devanagari Script has been added which are used for Hindi and Sanskrit language. It 
Closes #157, 
Closes #2147, 
Closes #1327

Devanagari Script and Hindi Language Layout Added 

---

app/src/main/kotlin/dev/patrickgold/florisboard/ime/editor/AbstractEditorInstance.kt

Fixes: #2806
@patrickgold would it be possible to add this to a v0.4 bugfix release?

Do not ignore flagTextNoSuggestions.

---

app/src/main/kotlin/dev/patrickgold/florisboard/FlorisImeService.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/AppPrefs.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/localization/LocalizationScreen.kt
app/src/main/res/values/strings.xml

Add toggle for keyboard label language

---

app/src/main/res/values/strings.xml

Change "Material you" to "Material You"

---

app/src/main/kotlin/dev/patrickgold/florisboard/FlorisImeService.kt
app/src/main/res/values/themes.xml

Add transparent navigation bar to android xml themes

---

app/src/main/kotlin/dev/patrickgold/florisboard/app/AppPrefs.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/keyboard/KeyboardManager.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/smartbar/quickaction/QuickAction.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/smartbar/quickaction/QuickActionArrangement.kt
app/src/main/res/values/strings.xml

Fixes: https://github.com/florisboard/florisboard/issues/84#issuecomment-2714622630

Add language switch option to smartbar

---

app/src/main/assets/ime/theme/org.florisboard.themes/stylesheets/floris_day.json
app/src/main/assets/ime/theme/org.florisboard.themes/stylesheets/floris_day_borderless.json
app/src/main/assets/ime/theme/org.florisboard.themes/stylesheets/floris_night.json
app/src/main/assets/ime/theme/org.florisboard.themes/stylesheets/floris_night_borderless.json
app/src/main/assets/ime/theme/org.florisboard.themes/stylesheets/floris_pure_night.json
app/src/main/assets/ime/theme/org.florisboard.themes/stylesheets/floris_pure_night_borderless.json
app/src/main/kotlin/dev/patrickgold/florisboard/ime/theme/FlorisImeThemeBaseStyle.kt

Fix inline autofill chip style

---

app/build.gradle.kts
app/src/main/kotlin/dev/patrickgold/florisboard/app/AppPrefs.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/devtools/DevtoolsScreen.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/smartbar/quickaction/QuickActionArrangement.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyData.kt
app/src/main/res/values/strings.xml
app/src/test/kotlin/dev/patrickgold/florisboard/ime/smartbar/quickaction/QuickActionArrangementTest.kt
app/src/test/kotlin/dev/patrickgold/florisboard/lib/ext/ExtensionAuthorTest.kt
app/src/test/kotlin/dev/patrickgold/florisboard/lib/kotlin/StringsTest.kt

Originally reported in Matrix group chat.

Fix Smartbar quick actions duplicating in prefs migration

---

app/build.gradle.kts

Fix version suffix missing minus delimiter

---

app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/theme/ThemeEditorScreen.kt
app/src/main/res/values/strings.xml

Small fixes in new theme editor

---

app/src/main/kotlin/dev/patrickgold/florisboard/ime/popup/PopupUiController.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboardLayout.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/theme/FlorisImeTheme.kt
lib/snygg/src/main/kotlin/org/florisboard/lib/snygg/SnyggPropertySetEditor.kt
lib/snygg/src/main/kotlin/org/florisboard/lib/snygg/SnyggTheme.kt
lib/snygg/src/main/kotlin/org/florisboard/lib/snygg/ui/SnyggUi.kt
lib/snygg/src/test/kotlin/org/florisboard/lib/snygg/SnyggThemeTest.kt

Fixes #2891
Fixes #2894 
Changes:
- Add fontSizeMultiplier functionality to underlying Snygg v2 engine

Fix font size multiplier not having any effect

---

app/src/main/assets/ime/theme/org.florisboard.themes/stylesheets/floris_day.json
app/src/main/assets/ime/theme/org.florisboard.themes/stylesheets/floris_day_borderless.json
app/src/main/assets/ime/theme/org.florisboard.themes/stylesheets/floris_night.json
app/src/main/assets/ime/theme/org.florisboard.themes/stylesheets/floris_night_borderless.json
app/src/main/assets/ime/theme/org.florisboard.themes/stylesheets/floris_pure_night.json
app/src/main/assets/ime/theme/org.florisboard.themes/stylesheets/floris_pure_night_borderless.json
app/src/main/kotlin/dev/patrickgold/florisboard/FlorisImeService.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/smartbar/CandidatesRow.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/smartbar/Smartbar.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/smartbar/quickaction/QuickActionButton.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/theme/FlorisImeThemeBaseStyle.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/theme/FlorisImeUi.kt
app/src/main/res/values/strings.xml
lib/snygg/src/main/kotlin/org/florisboard/lib/snygg/ui/SnyggBox.kt

Fixes #2887
Fixes #2881
Changes:
- Add element `smartbar-action-tile-icon`
- Add element `smartbar-action-tile-text`
- Add element `smartbar-candidate-word-text`
- Add element `smartbar-candidate-word-secondary-text`
- Add element `smartbar-candidate-clip-icon`
- Add element `smartbar-candidate-clip-text`
- Improve default styles for Smartbar in general

Fix Smartbar styles (actions, candidates, ...)

---

app/build.gradle.kts
app/src/main/kotlin/dev/patrickgold/florisboard/ime/keyboard/KeyboardManager.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/TextInputLayout.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboardLayout.kt
lib/color/src/main/kotlin/org/florisboard/lib/color/ColorMappings.kt
lib/snygg/src/main/kotlin/org/florisboard/lib/snygg/ui/SnyggUi.kt

Also enable Compose strong skipping mode
Fixes #2884

Fix Snygg and IME UI state bugs regarding theme state updates

---

app/src/main/kotlin/dev/patrickgold/florisboard/app/AppPrefs.kt

Fix one-handed button migration

---

.github/workflows/android.yml

Reverts florisboard/florisboard#2917

Revert "Fix ignored paths not applied to `pull_request` in workflow"

---

app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/theme/ThemeEditorScreen.kt

Fix theme editor navbar color bug

---

app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/keyboard/InputFeedbackScreen.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/clipboard/FlorisCopyToClipboardActivity.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/editor/EditorInstance.kt
app/src/main/kotlin/dev/patrickgold/florisboard/lib/util/NetworkUtils.kt
app/src/main/res/values/strings.xml
lib/android/src/main/kotlin/org/florisboard/lib/android/AndroidVersion.kt

Remove obsolete api level checks that were unused by raising the minimum api version,

Remove obsolete api level check and simplify logic

---

app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/theme/EditPropertyDialog.kt
lib/snygg/schemas/stylesheet.schema.json
lib/snygg/src/main/kotlin/org/florisboard/lib/snygg/value/SnyggUriValue.kt

Fix files with spaces causing UI issues

---

app/src/main/assets/ime/keyboard/org.florisboard.localization/popupMappings/ast.json

Added some tweaks for H, L, N and R letters

Update "ast" layout

---

README.md

Add the apk signing certificate hashes

---

app/src/main/kotlin/dev/patrickgold/florisboard/ime/media/emoji/EmojiSuggestionProvider.kt

This PR reworks the emoji suggestion algorithm. Emojis that only had their name.defined, not their keywords, were previously not found.
Some examples comparing 0.5.0-beta04 with rc01:
Input | Current | New
---|---|---
:eye | 😃 😄 😁 😊 😍 | 👁️ 👀 🎯 👁️‍🗨️ 🙄
:eyes | 😃 😄 😁 😊 😍 | 👀 🙄 😵 😃 😻
:cold | 😅 😷 🥶 😰 😓 | 🥶 😅 😷 😰 😓
:bubble | 💬 👁️‍🗨️ 🗨️ 🗯️ 💭 | 🧋 🫧 🗨️ 🗯️ 👁️‍🗨️
:glass | 🥸 😎 🥛 🍷 🍸 | 👓 🍷 🕶️ 🥛 🥃
:ear | 😂 🥰 😍 🥲 🥹 | 👂 🐻 🍐 ⚙️ 🙀

Improve emoji suggestion weighting

---

app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/advanced/RestoreScreen.kt

Reported here: https://github.com/florisboard/florisboard/issues/2342#issuecomment-3166164991

Fix restore failure when no preferences file is found

---

app/src/main/res/values/strings.xml

Remove string length limitation

---

app/src/main/kotlin/dev/patrickgold/florisboard/FlorisImeService.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/theme/ThemeManager.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/theme/WallpaperChangeReceiver.kt

Listen for configuration changes to update ime theme

---

app/src/main/kotlin/dev/patrickgold/florisboard/app/ext/ExtensionEditScreen.kt
app/src/main/kotlin/dev/patrickgold/florisboard/app/settings/theme/ThemeScreen.kt
app/src/main/kotlin/dev/patrickgold/florisboard/ime/theme/ThemeManager.kt

Fixes a state bug introduced with https://github.com/florisboard/florisboard/commit/1132eaf59b004e2e6399707e8857894d54c592cc
Closes #3043

Fix theme updates not properly propagating after save

---

app/src/main/kotlin/dev/patrickgold/florisboard/ime/keyboard/ComputingEvaluator.kt

Use different icon for paste action
